src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_BUPicklist__c</fullName>
        <defaultValue>$User.ER_BUText__c</defaultValue>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BUPicklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ER_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Legal_Form__c</fullName>
        <description>Legal form of the company</description>
        <label>Legal Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Other_Fiscal_ID__c</fullName>
        <label>Other Fiscal ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Registration_Number__c</fullName>
        <label>Company Registration Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BUPicklist__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Suspect</fullName>
                </value>
                <value>
                    <fullName>No potential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Company_Type__c</fullName>
        <label>Company Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Institution</fullName>
                </value>
                <value>
                    <fullName>Private (work for Institution)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Fiscal_Code__c</fullName>
        <label>Fiscal Code</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Legal_Form__c</fullName>
        <label>Legal Form</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Legal_Form</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ER_Store__c.object
<CustomObject>
    <fields>
        <fullName>ER_BUPicklist__c</fullName>
        <defaultValue>$User.ER_BUText__c</defaultValue>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Store_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accept</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Store__c</fullName>
        <label>Store</label>
        <referenceTo>ER_Store__c</referenceTo>
        <relationshipLabel>Store line Items</relationshipLabel>
        <relationshipName>Store_line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Line Item</label>
    <nameField>
        <displayFormat>SLI-{0000000}</displayFormat>
        <label>Store Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/ER_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Apparel</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Biotechnology</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Energy</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Environmental</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Food &amp; Beverage</fullName>
    </customValue>
    <customValue>
        <fullName>Furniture</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Station</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Lottery</fullName>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and advertising agencies</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Mining</fullName>
    </customValue>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/Test_APIT00_RelatedListController.cls
@isTest
public class Test_APIT00_RelatedListController {
  
    @isTest static void testAccountHirerchyFalse(){
    
     Account parent1 = new Account (
            Name = 'Parent1',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50
           
        );
    
    insert parent1;
    
      Account child1 = new Account (
            Name = 'child1',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
            ParentId = parent1.id
          
        );
        
    insert child1;
 
     APIT00_RelatedListController.fetchRecs(parent1.id, 'Account', 'ParentID', '', 'false' ,'ER_VAT_Number__c', 'Name', 'IT_Company_Type__c', 'IT_Industry__c');
         }
    
     @isTest static void testAccountHirerchyTrue (){
    
     Account parent1 = new Account (
            Name = 'Parent1',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50
            
        );
    
    insert parent1;
    
      Account child1 = new Account (
            Name = 'child1',
           ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
           
            ParentId = parent1.id
        );
        
    insert child1;
 
     APIT00_RelatedListController.fetchRecs(parent1.id, 'Account', 'ParentID', '', 'true' ,'ER_VAT_Number__c', 'Name', 'IT_Company_Type__c', 'IT_Industry__c');
         }
    
     @isTest static void testAccountStrCriteria(){
    
     Account parent1 = new Account (
            Name = 'Parent1',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50
           
        );
    
    insert parent1;
    
      Account child1 = new Account (
            Name = 'child1',
          ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
            ParentId = parent1.id
        );
        
    insert child1;
 
     APIT00_RelatedListController.fetchRecs(parent1.id, 'Account', 'ParentID', 'AND Name = \'AccountTest\'', 'false' ,'ER_VAT_Number__c', 'Name', 'IT_Company_Type__c', 'IT_Industry__c');
         }
    
    
    @isTest(seeAllData=false) static void testAccountHirerchyFalseLimit4(){
    
        List < sObject > listsObjectAccount = new List < sObject >();
        
     Account parent1 = new Account (
            Name = 'Parent1',
           ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50
            
        );
    
    insert parent1;
    
      Account child1 = new Account (
            Name = 'child1',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
            ParentId = parent1.id
        );
        
        listsObjectAccount.add(child1);
        
         Account child2 = new Account (
            Name = 'child2',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
            ParentId = parent1.id
        );
        
     listsObjectAccount.add(child2);
        
           Account child3 = new Account (
            Name = 'child3',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
            ParentId = parent1.id
        );
        
     listsObjectAccount.add(child3);
        
          Account child4 = new Account (
            Name = 'child4',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
            ParentId = parent1.id
        );
        
     listsObjectAccount.add(child4);
        
         Account child5 = new Account (
            Name = 'child5',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
            ParentId = parent1.id
        );
        
     listsObjectAccount.add(child5);
        
         Account child6 = new Account (
            Name = 'child6',
            ER_VAT_Number__c   = '02824320176',
            IT_Fiscal_Code__c  = '01014660417',
            IT_Company_Type__c = 'Private',
             ER_Registration_Number__c = 'ER_Registration_Number__c',
            IT_Legal_Form__c   = 'ASS',
            IT_Industry__c     = '106',
            ER_BUPicklist__c  = 'IT',
            Phone = '3336574564',
            ER_Legal_Form__c = 'LegalForm',
            ER_Industry__c ='Energy',
            ER_Other_Fiscal_ID__c = '01014660417',
            BillingStreet = 'Billing',
            BillingCity = 'Billing',
            BillingState = 'Billing',
            BillingPostalCode = 'Billing',
            BillingCountry  = 'Billing',
            NumberOfEmployees = 50,
            ParentId = parent1.id
        );
        
     listsObjectAccount.add(child6);
        
       
        
        insert listsObjectAccount;
        
        System.debug('Id APrent classe Test ' + parent1.id);
        Test.startTest();
     APIT00_RelatedListController.fetchRecs(parent1.id, 'Account', 'ParentID', '', 'false' ,'ER_VAT_Number__c', 'Name', 'IT_Company_Type__c', 'IT_Industry__c');
        Test.stopTest();   
    }
    
    @isTest static void customObjectHierarchyFalse(){
        
        ER_Store__c store = new ER_Store__c(
        Name = 'Store Test',
       ER_Street__c = 'Street 000 271100'
        );
        insert store;
        
        ER_Store_Line_Item__c storeItem = new ER_Store_Line_Item__c(
        ER_Status__c = 'Accept',
        ER_Store__c = store.id 
        );
        insert storeItem;
        
       APIT00_RelatedListController.fetchRecs(store.id, 'ER_Store_Line_Item__c', 'ER_Store__c', '', 'false' ,'', 'Name', '', '');
        }
    
    @isTest static void customObjectHierarchyTrue(){
        
        ER_Store__c store = new ER_Store__c(
        Name = 'Store Test',
       ER_Street__c = 'Street 000 271100'
        );
        insert store;
        
        ER_Store_Line_Item__c storeItem = new ER_Store_Line_Item__c(
        ER_Status__c = 'Accept',
        ER_Store__c = store.id 
        );
        insert storeItem;
        
       APIT00_RelatedListController.fetchRecs(store.id, 'ER_Store_Line_Item__c', 'ER_Store__c', '', 'True' ,'', 'Name', '', '');
        }
}