src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Segment__c</fullName>
        <label>Local Client Segmentation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Small merchants</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>LNA</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>LNA_KAM_001</fullName>
                </value>
                <value>
                    <fullName>LNA_KAM_002</fullName>
                </value>
                <value>
                    <fullName>LNA_KAM_003</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BB</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BA1</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_NR</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_TT</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BA2</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_KE</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_PO</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_ZA</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BA3</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BA4</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_TN</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_TN1</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_KE</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_TT</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_NR</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_PO</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_BB</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_TT2</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_ZA</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_TN2</fullName>
                </value>
                <value>
                    <fullName>SME_OTH_001</fullName>
                </value>
                <value>
                    <fullName>SME_TLS_001</fullName>
                </value>
                <value>
                    <fullName>SME_TLS_002</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                    <label>SUPER A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Delivery_Site__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Delivery Sites</relationshipLabel>
        <relationshipName>Delivery_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Delivery Site</label>
    <nameField>
        <label>Delivery Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Distribution_Point__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/ER_Distribution_Point__c/fields/ER_Delivery_Site__c.field-meta.xml
<CustomField>
    <fullName>ER_Delivery_Site__c</fullName>
    <label>Delivery Site</label>
    <referenceTo>ER_Delivery_Site__c</referenceTo>
    <relationshipLabel>Distribution Points</relationshipLabel>
    <relationshipName>Distribution_Points</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_Control__c.object
<CustomObject>
    <fields>
        <fullName>IT_CLN_Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Control</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Control</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_ControlUpdateTrigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>IT_ControlTreiggerUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ControlTreiggerUpdate</label>
        <type>Checkbox</type>
    </fields>
    <label>ControlUpdateTrigger</label>
</CustomObject>

src/classes/APIT22_CardInterfaceController_Test.cls
@isTest
public class APIT22_CardInterfaceController_Test {
    @isTest static void linkController() {
        IT_ControlUpdateTrigger__c settings = IT_ControlUpdateTrigger__c.getOrgDefaults();
        settings.IT_ControlTreiggerUpdate__c = true;
        insert settings;
        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        accountTest.ER_Segment__c = 'S';
        insert accountTest;
        Contact contactTest = APIT14_DataFactory.create_Contact(accountTest.Id);
        insert contactTest;
        ER_Financial_Center__c FinancialTest = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest.ER_Card_Operational_System_ID__c = 'Tes2w';
        FinancialTest.ER_Type__c = 'Client'; 
        insert FinancialTest;
        ER_Delivery_Site__c delSite = APIT14_DataFactory.create_DeliverySite(FinancialTest.id , accountTest.Id);
        insert delSite;
        ER_Distribution_point__c distPoint = APIT14_DataFactory.create_DistributionPoint(FinancialTest.id, delSite.id);
        insert DistPoint;
        IT_Control__c contr = new IT_Control__c(IT_CLN_Service__c = '3');
        insert contr;
        APIT22_CardInterfaceController.fetchDPData(distPoint.id);
        APIT22_CardInterfaceController.fetchDataType(distpoint.id, '3');
    }
}