src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>ER_Employee__c</referenceTo>
        <relationshipLabel>Individual</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Match_Legal_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Legal to Head Office address?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BUPicklist__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Suspect</fullName>
                </value>
                <value>
                    <fullName>No potential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>ER_Company_Account_RT</fullName>
        <active>true</active>
        <description>Merge of Merchant and Client Record types into Company</description>
        <label>Company</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>ER_Asset_Type__c</fullName>
        <label>Asset Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ER_Multicard</fullName>
                    <label>Multi-Wallet</label>
                </value>
                <value>
                    <fullName>ER_Mono-Wallet</fullName>
                    <label>Mono-Wallet</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>ER_Employee__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ER_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>ER_Employee__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>ER_Store__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Bank_Account__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/ER_Bank_Account__c/fields/ER_Bank_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>ER_Bank_Account_Status__c</fullName>
    <label>Bank Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Bank_Account__c/fields/ER_Financial_Center__c.field-meta.xml
<CustomField>
    <fullName>ER_Financial_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Center</label>
    <referenceTo>ER_Financial_Center__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ER_ContractLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ER_Solution__c</fullName>
        <formula>ER_Product2__r.ER_Solution_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution</label>
        <type>Text</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Contract Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Employee__c.object
<CustomObject>
    <fields>
        <fullName>ER_Professional_Email__c</fullName>
        <label>Professional Email</label>
        <type>Email</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Bank_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Account</label>
        <referenceTo>ER_Bank_Account__c</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers_BankAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_City__c</fullName>
        <label>Billing City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Country__c</fullName>
        <label>Billing Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Zip_Code__c</fullName>
        <label>Billing Zip Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Store__c.object
<CustomObject>
    <fields>
        <fullName>ER_City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Merchant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Start_date__c</fullName>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pizzeria</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Snack</fullName>
                </value>
                <value>
                    <fullName>Hypermarket</fullName>
                </value>
                <value>
                    <fullName>Supermarket</fullName>
                </value>
                <value>
                    <fullName>Convenience stores</fullName>
                </value>
                <value>
                    <fullName>Fast food</fullName>
                </value>
                <value>
                    <fullName>Cantine</fullName>
                </value>
                <value>
                    <fullName>Gas stations</fullName>
                </value>
                <value>
                    <fullName>Grocery</fullName>
                </value>
                <value>
                    <fullName>Discounter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Store_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>ER_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Store line Items</relationshipLabel>
        <relationshipName>Store_line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accept</fullName>
                </value>
                <value>
                    <fullName>Decline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Store__c</fullName>
        <label>Store</label>
        <referenceTo>ER_Store__c</referenceTo>
        <relationshipLabel>Store line Items</relationshipLabel>
        <relationshipName>Store_line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Store Line Item</label>
    <nameField>
        <displayFormat>SLI-{0000000}</displayFormat>
        <label>Store Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Solution</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APER07_UtilityTestMethod.cls
/*
----------------------------------------------------------------------
-- - Name          : APER07_UtilityTestMethod
-- - Author        : OLA
-- - Description   : utility class to insert data
--
-- Date         Name                Version     Remarks
-- -----------  -----------         --------    ---------------------------------------
--  JAN-2019       OLA                 1.0         Initial version
---------------------------------------------------------------------------------------
*/
public class APER07_UtilityTestMethod {

  /*************************************
  *               Asset
  **************************************/

  //provide a single Asset
  public static Asset getAsset(String name, String recordTypeDeveloperName, String assetType) {
    return new Asset(
             Name = name,
             Status = Label.LAB_SF_ASSET_Status_Active,
             recordtypeid = Schema.SObjectType.Asset.getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId(),
             ER_Asset_Type__c = assetType
           );
  }

  /*************************************
  *               Case
  **************************************/

  //provide a single Case
  public static Case getCase(String recordTypeDeveloperName) {
    return new Case(
             recordtypeid = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(recordTypeDeveloperName).getRecordTypeId()
           );
  }


  /*************************************
  *           ER_Employee__c
  **************************************/

  //provide a single Employee
  public static ER_Employee__c getEmployee() {
    return new ER_Employee__c(
             name = 'testEmployee',
             ER_Professional_Email__c = 'test@test.com'
           );
  }

  /*************************************
  *               Account
  **************************************/

  //provide a single Company
  public static Account getCompany(String name) {
    return new Account(
             recordtypeid = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('ER_Company_Account_RT').getRecordTypeId(),
             ER_Match_Legal_Address__c = true,
             Name = name
           );
  }

  /*************************************
  *               Contact
  **************************************/

  public static Contact getContact(String recordType, String firstName, String lastName) {
    return new Contact(
             FirstName = firstName ,
             LastName = lastName ,
             recordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(recordType).getRecordTypeId()
           );
  }
    
  /*************************************
  *               Financial Center
  **************************************/

  public static ER_Financial_Center__c getFinancialCenter(String name, String accountId, String fcType, String street, String city,String zipCode, String country) {
    return new ER_Financial_Center__c(
             Name = name,
             ER_Account_Name__c = accountId,
             ER_Type__c = fcType,
             ER_Street__c = street,
             ER_City__c = city,
             ER_Zip_Code__c = zipCode,
             ER_Country__c = country
           );
  }
      
  /*************************************
  *               Bank Account
  **************************************/

    public static ER_Bank_Account__c getBankAccount(String finCenterId, String name, String status, String city, String street,String iban) {
        return new ER_Bank_Account__c(
            Name = name,
            ER_Financial_Center__c = finCenterId,
            ER_Bank_Account_Status__c = status,
            ER_Bank_City__c = city,
            ER_IBAN__c = iban
        );
    }  

  /*************************************
  *               Store
  **************************************/

  public static ER_Store__c getStore(String name, String accountId, String financialCenterId, Date startDate, String street, String city,String zipCode, String country) {
    return new ER_Store__c(
             Name = name,
             ER_Merchant__c = accountId,
             ER_Financial_Center__c = financialCenterId,
             ER_Start_date__c = startDate,
             ER_Street__c = street,
             ER_City__c = city,
             ER_Zip_Code__c = zipCode,
             ER_Country__c = country
           );
  }

  /*************************************
  *               Store Line Item
  **************************************/

  public static ER_Store_Line_Item__c getStoreLineItem(String storeId, String status, String solutionId) {
    return new ER_Store_Line_Item__c(
             ER_Store__c = storeId,
             ER_Status__c = status,
             ER_Solution__c = solutionId
           );
  }
    
  /*************************************
  *               Product
  **************************************/

  //provide a single Client
  public static Product2 getProduct(String codeEDG) {
    return new Product2(
             Name = 'testProduct',
             ER_EDG_Product_Ref__c = codeEDG
           );
  }

  /*************************************
  *               Opportunity
  **************************************/

  public static Opportunity getOpportunity(String recordType, String name) {
    return new Opportunity(
             Name = name ,
             recordtypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(recordType).getRecordTypeId(),
             StageName = Label.LABS_SF_Opp_Status_Qualification,
             CloseDate = Date.today().addMonths(1)
           );
  }

  /*************************************
  *        Opportunity Line Item
  **************************************/

  public static OpportunityLineItem getOpportunityLineItem(String opportunityId, String pricebookEntryId) {
    return new OpportunityLineItem(
             opportunityId = opportunityId,
             pricebookEntryId = pricebookEntryId,
             UnitPrice = 1,
             ER_Percentage__c = 2,
             Quantity = 1
           );
  }

  /*************************************
  *               Quote
  **************************************/

  public static Quote getQuote(String recordType, String name, String opportunityId, String priceBookId) {
    return new Quote(
             Name = name,
             OpportunityId = opportunityId,
             Pricebook2Id = priceBookId,
             recordtypeId = Schema.SObjectType.Quote.getRecordTypeInfosByDeveloperName().get(recordType).getRecordTypeId(),
             Status = Label.LABS_SF_Quote_Status_Draft,
             ExpirationDate = Date.today().addMonths(1)
           );
  }

  /*************************************
  *        Quote Line Item
  **************************************/

  public static QuoteLineItem getQuoteLineItem(String quoteId, String pricebookEntryId) {
    return new QuoteLineItem(
             QuoteId = quoteId,
             pricebookEntryId = pricebookEntryId,
             UnitPrice = 1,
             ER_Percentage__c = 2,
             Quantity = 1
           );
  }

  /*************************************
  *         Service (Product2)
  **************************************/

  public static Product2 getservice(String name, String solutionId) {
    return new Product2(
             Name = name,
             ER_Type__c = 'service',
             ER_Solution__c = solutionId,
             IsActive = true
           );
  }

  /*************************************
  *         Solution (Product2)
  **************************************/

  public static Product2 getsolution(String name) {
    return new Product2(
             Name = name,
             ER_Type__c = 'solution',
             IsActive = true
           );
  }

  /*************************************
  *         PriceBook
  **************************************/

  public static PriceBook2 getpriceBook() {
    return new PriceBook2(
             Id = Test.getStandardPricebookId(),
             ER_Business_Unit__c = APER10_User_Management.userBU,
             IsActive = true
           );
  }

  /*************************************
  *         PriceBookEntry
  **************************************/

  public static PriceBookEntry getpriceBookEntry(String priceBookId, String productId) {
    return new PriceBookEntry(
             Pricebook2Id = priceBookId,
             Product2Id = productId,
             UnitPrice = 1,
             ER_Percentage__c = 1,
             IsActive = true,
             ER_ValueType__c = Label.LABS_SF_Opp_Product_Currency
           );
  }

  /*************************************
  *               Contact
  **************************************/

  public static Contract getContract(String accountId, Date startDate, String status, String priceBookId) {
    return new Contract(
      AccountId = accountId,
      StartDate = startDate,
      Status = status,
      PriceBook2Id = priceBookId
    );
  }

  /*************************************
  *           Contract Line Item
  **************************************/
  public static ER_ContractLineItem__c getContractLineItem(String contractId, String product2Id,String priceBookEntryId, Integer quantity, Decimal unitPrice) {
    return new ER_ContractLineItem__c(
      ER_Contract__c = contractId,
      ER_Product2__c = product2Id,
      ER_PricebookEntryId__c = priceBookEntryId,
      ER_Quantity__c = quantity,
      ER_UnitPrice__c = unitPrice
    );
  }
}