src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IT_Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_Group__c.object
<CustomObject>
    <fields>
        <fullName>IT_Group_Code__c</fullName>
        <externalId>true</externalId>
        <label>Group Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_Group_Code__c.object
<CustomObject>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Code</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Groups Code</relationshipLabel>
        <relationshipName>Groups_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Client_Code__c</fullName>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Group_Code__c</fullName>
        <label>Group Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>IT_Group__c</referenceTo>
        <relationshipLabel>Groups Code</relationshipLabel>
        <relationshipName>Groups_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Code</label>
    <nameField>
        <label>Group Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BAIT01_BatchGroupAssociations_Test.cls
@isTest
public class BAIT01_BatchGroupAssociations_Test {
    @isTest
    static void batchGroupAssociations(){
        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        accountTest.ER_VAT_Number__c = '02554698475';
        insert accountTest;
        Contact contactTest = APIT14_DataFactory.create_Contact(accountTest.Id);
        contactTest.IT_Code__c = 'StringString';
        insert contactTest;
        ER_Financial_Center__c FinancialTest = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest.ER_Card_Operational_System_ID__c = 'Tes2w';
        FinancialTest.ER_Type__c = 'Client'; 
        FinancialTest.IT_Financial_Center__c = '445566';
        insert FinancialTest;
        IT_Group_Code__c groupCodeTest = APIT14_DataFactory.create_GroupCode(FinancialTest.Id);
        groupCodeTest.IT_Client_Code__c = '445566';
        insert groupCodeTest;
        IT_Group__c groupTest = APIT14_DataFactory.create_Group(FinancialTest.Id);
        insert groupTest;
        
        BAIT01_BatchGroupAssociations batchRun = new BAIT01_BatchGroupAssociations();
        database.executebatch(batchRun,10);

    }
}