src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Segment__c</fullName>
        <label>Local Client Segmentation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Small merchants</fullName>
                </value>
                <value>
                    <fullName>MM</fullName>
                </value>
                <value>
                    <fullName>LNA</fullName>
                </value>
                <value>
                    <fullName>Public</fullName>
                </value>
                <value>
                    <fullName>LNA_KAM_001</fullName>
                </value>
                <value>
                    <fullName>LNA_KAM_002</fullName>
                </value>
                <value>
                    <fullName>LNA_KAM_003</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BB</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BA1</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_NR</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_TT</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BA2</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_KE</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_PO</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_ZA</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BA3</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_BA4</fullName>
                </value>
                <value>
                    <fullName>MSM_FSL_TN</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_TN1</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_KE</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_TT</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_NR</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_PO</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_BB</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_TT2</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_ZA</fullName>
                </value>
                <value>
                    <fullName>SME_BRA_TN2</fullName>
                </value>
                <value>
                    <fullName>SME_OTH_001</fullName>
                </value>
                <value>
                    <fullName>SME_TLS_001</fullName>
                </value>
                <value>
                    <fullName>SME_TLS_002</fullName>
                </value>
                <value>
                    <fullName>S</fullName>
                    <label>SUPER A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IT_Circuit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Circuit</label>
        <referenceTo>IT_Circuit__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Product__c</fullName>
        <formula>CASE(TEXT(IT_Financial_Center__r.IT_Service__c),
&quot;0V&quot;,&quot;FLEX TICKET RESTAURANT&quot;,
&quot;1G&quot;,&quot;COMPLIMENTS PREMIUM PROMO&quot;,
&quot;1F&quot;,&quot;COMPLIMENTS SELECTION PROMO&quot;,
&quot;1A&quot;,&quot;POSTEPAY LUNCH SMART&quot;,
&quot;0O&quot;,&quot;FLEX TICKET SERVICE CARD&quot;,
&quot;1B&quot;,&quot;FLEXBENEFIT&quot;,
&quot;0W&quot;,&quot;E-LUNCH SMART&quot;,
&quot;3&quot;,&quot;TICKET RESTAURANT&quot;,
&quot;4&quot;,&quot;TICKET SERVICE&quot;,
&quot;C&quot;,&quot;TICKET RESTAURANT CARD&quot;,
&quot;6&quot;,&quot;CLEAN WAY&quot;,
&quot;8&quot;,&quot;GRANT FRIEND&quot;,
&quot;9&quot;,&quot;TICKET TRANSPORT&quot;,
&quot;B&quot;,&quot;TICKET RESTAURANT GOLD&quot;,
&quot;D&quot;,&quot;TICKET RESTAURANT MAX&quot;,
&quot;F&quot;,&quot;DOMI PHONE&quot;,
&quot;G&quot;,&quot;PEOPLE ONE&quot;,
&quot;R&quot;,&quot;TICKET RESTAURANT SMART&quot;,
&quot;0G&quot;,&quot;COMPLIMENTS PREMIUM&quot;,
&quot;0F&quot;,&quot;COMPLIMENTS SELECTION&quot;,
&quot;0H&quot;,&quot;VIRTUAL COMPLIMENTS&quot;,
&quot;0I&quot;,&quot;TICKET SERVICE CARNET&quot;,
&quot;W&quot;,&quot;RISTOCHEF CARD&quot;,
&quot;0P&quot;,&quot;TICKET FAMILY&quot;,
&quot;0Q&quot;,&quot;TICKET CULTURE&quot;,
&quot;Z1&quot;,&quot;Edenred CUSTOMER ACCOUNTS&quot;,
&quot;Z2&quot;,&quot;Ristochef CUSTOMER ACCOUNTS&quot;,
&quot;Z3&quot;,&quot;E-LUNCH ACCOUNTING CLIENTS&quot;,
&quot;1W&quot;,&quot;FLEXBENEFIT REIMBURSMENT&quot;,
&quot;1X&quot;,&quot;TICKET WELFARE&quot;,
&quot;2A&quot;,&quot;RETEITALIA CARD&quot;,
&quot;2B&quot;,&quot;UTA CARD&quot;,
&quot;2F&quot;,&quot;COMPLIMENTS SELECTION eVouchers&quot;,
&quot;2G&quot;,&quot;COMPLIMENTS PREMIUM E-VOUCHER&quot;,
&quot;1D&quot;,&quot;TICKET TRANSPORT SMART&quot;,
&quot;1V&quot;,&quot;TICKET RESTAURANT MAX SMART&quot;,
&quot;0J&quot;,&quot;COMPLIMENTS SPENDING&quot;,
&quot;1N&quot;,&quot;FLEXBENEFIT SKILL&quot;,
&quot;1Q&quot;,&quot;FLEX TICKET SERVICE&quot;,
&quot;1R&quot;,&quot;TICKET RESTAURANT DIGITAL&quot;,
&quot;1Y&quot;,&quot;FLEXBENEFIT ALLOCATION OF FUNDS&quot;,
&quot;2K&quot;,&quot;COMPLIMENTS SEL. EASY eVouchers&quot;,
&quot;1Z&quot;,&quot;COMPLIMENTS EXPERIENCE PROMO&quot;,
&quot;2J&quot;,&quot;COMPLIMENTS EXPENSE E-VOUCHER&quot;,
&quot;0K&quot;,&quot;COMPLIMENTS EASY SELECTION&quot;,
&quot;2C&quot;,&quot;PARTNER ONLINE&quot;,
&quot;2X&quot;,&quot;VAT TICKET WELFARE&quot;,
&quot;1H&quot;,&quot;COMPLIMENTS EXPERIENCE&quot;,
&quot;1L&quot;,&quot;FLEXBENEFIT CHECK&quot;,
&quot;1M&quot;,&quot;FLEXBENEFIT CARE&quot;,
&quot;1S&quot;,&quot;CITY TIME PLUS SMART&quot;,
&quot;1T&quot;,&quot;CITY TIME PLUS (PRODOTTO CARTACEO)&quot;,
&quot;&quot;
)

/*IT_Financial_Center__r.IT_Product2__r.Name*/</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>IT_Client_Support_Case_RT</fullName>
        <active>true</active>
        <businessProcess>Support Process</businessProcess>
        <label>IT Client Support Case RT</label>
    </recordTypes>
    <recordTypes>
        <fullName>IT_Client_Welfare_Provisioning_Case_RT</fullName>
        <active>true</active>
        <businessProcess>Support Process</businessProcess>
        <label>IT Client Welfare Provisioning Case RT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flexbenefit</fullName>
                </value>
                <value>
                    <fullName>Ticket Restaurant</fullName>
                </value>
                <value>
                    <fullName>Ticket Restaurant Smart</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Circuit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Circuit</label>
        <referenceTo>IT_Circuit__c</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_Circuit__c.object
<CustomObject>
    <label>Circuit</label>
    <nameField>
        <label>Circuit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circuits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_ControlUpdateTrigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>IT_ControlTreiggerUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ControlTreiggerUpdate</label>
        <type>Checkbox</type>
    </fields>
    <label>ControlUpdateTrigger</label>
</CustomObject>

force-app/main/default/classes/APIT15_CaseTriggerHandler_Test.cls
@isTest
public class APIT15_CaseTriggerHandler_Test {
    @isTest (seeAllData = true)
    static void TestCaseContactLink() {
        IT_ControlUpdateTrigger__c settings = IT_ControlUpdateTrigger__c.getOrgDefaults();
        settings.IT_ControlTreiggerUpdate__c = true;
        insert settings;
        List<Case> caseList = new List<Case>();
        User testUser = APIT14_DataFactory.create_User();
        Account testAcco2 = APIT14_DataFactory.create_PersonAccount();
        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        accountTest.ER_Segment__c = 'S';
        insert accountTest;
        
        Contact contactTest = APIT14_DataFactory.create_Contact(accountTest.Id);
        insert contactTest;
        Contract contractTest = APIT14_DataFactory.create_Contract(accountTest.Id);
        contractTest.ER_Contract_External_ID__c = 'Tes2w';
        insert contractTest;
        IT_Circuit__c circuitTest = APIT14_DataFactory.create_Circuit(accountTest.Id);
        insert circuitTest;
        ER_Financial_Center__c FinancialTest = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest.ER_Card_Operational_System_ID__c = 'Tes2w';
        FinancialTest.ER_Type__c = 'Client'; 
        insert FinancialTest;
        Entitlement EntitlementTest = APIT14_DataFactory.create_Entitlement(accountTest.Id);
        insert EntitlementTest;
        Case caseTest = APIT14_DataFactory.create_Case(accountTest.Id);
        caseTest.Subject = '123456';
        caseTest.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('IT_Client_Welfare_Provisioning_Case_RT').getRecordTypeId();
        //insert caseTest;
        caseList.add(caseTest);
        Case caseTest2 = APIT14_DataFactory.create_Case(accountTest.Id);
        caseTest2.Subject = '123456';
        caseTest2.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('IT_Client_Support_Case_RT').getRecordTypeId();
        caseTest2.SuppliedEmail = 'test@test.test';
        //insert casetest2;
        caseList.add(caseTest2);

        Case caseTest3 = APIT14_DataFactory.create_Case(accountTest.Id);
        caseTest3.Subject = '7890';
        caseTest3.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('IT_Client_Support_Case_RT').getRecordTypeId();
        //insert casetest3;
        caseList.add(caseTest3);
        Case caseTest4 = APIT14_DataFactory.create_Case(accountTest.Id);
        casetest4.Accountid = null;
        casetest4.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('IT_Client_Support_Case_RT').getRecordTypeId();
        //insert casetest4;
        caseList.add(caseTest4);
        Case caseTest5 = APIT14_DataFactory.create_Case(accountTest.Id);
        caseTest5.Subject = '12345678901';
        casetest5.IT_Financial_Center__c = FinancialTest.id;
        //casetest5.IT_Product__c = 'Flexbenefit';
        casetest5.IT_Circuit__c = null;
        casetest5.Origin = 'Email';
        casetest5.EntitlementId = EntitlementTest.id;
        casetest5.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('IT_Client_Support_Case_RT').getRecordTypeId();
        //insert casetest5;
        caseList.add(caseTest5);
        insert caseList;
        
        casetest2.status = 'In_Progress';
        casetest2.SlaStartDate = system.now() - 1;
        update casetest2; 
        system.debug('case5 ' +casetest5);
        List<Case> caseObj = [select id, casenumber from case where id = : casetest4.id];
        EmailMessage testMail = APIT14_DataFactory.create_Emailmessage(casetest5.id);
        //TestMail.fromAddress = 'moreno.bonini@ellysse.it';
        //TestMail.toAddress = 'assistenza.test-it@edenred.com';
        Testmail.Subject = '[JIRA] (2345678) '+caseObj[0].CaseNumber+'-Test email broken alpha beta gamma';
        TestMail.TextBody = 'alpha beta gamma';
        system.debug('EMAIL SUBJECT:: ' +Testmail.Subject);
        insert testMail;
        MilestoneType[] mtLst = [SELECT Id, Name FROM MilestoneType LIMIT 1]; 
        APIT06_MilestoneTimeCalculator calculator = new APIT06_MilestoneTimeCalculator();
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new CTIMock());
        
        Integer actualTriggerTime = calculator.calculateMilestoneTriggerTime(casetest5.Id, mtLst[0].Id);
        Integer actualTriggerTime2 = calculator.calculateMilestoneTriggerTime(casetest3.Id, mtLst[0].Id);
        APIT15_CaseTriggerHandler.CTICallout(JSON.serialize(casetest5));
        APIT15_CaseTriggerHandler.isfirsttime = true;
        APIT15_CaseTriggerHandler.CTICalloutClosedCase(JSON.serialize(casetest5));
        
        test.stopTest();
    }    
    


    public class CTIMock implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"animals": ["majestic badger", "fluffy bunny", "scary bear", "chicken", "mighty moose"]}');
            response.setStatusCode(200);
            return response; 
        }
    }
}