src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Creation_date_in_OS__c</fullName>
        <description>Use as a reference for EDG data creation</description>
        <label>Creation date in OS</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ER_Last_date_of_Sync__c</fullName>
        <description>which hold the latest date/time when info was sent to the OS</description>
        <label>Last date of Sync</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit_2__c</fullName>
        <defaultValue>$User.ER_BUText__c</defaultValue>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Last_date_of_Sync__c</fullName>
        <description>which hold the latest date/time when info was sent to the OS</description>
        <label>Last date of Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CZ_AcademicTitle__c</fullName>
        <label>Academic Title</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>as.</fullName>
                </value>
                <value>
                    <fullName>CSc.</fullName>
                </value>
                <value>
                    <fullName>DiS.</fullName>
                </value>
                <value>
                    <fullName>doc.</fullName>
                </value>
                <value>
                    <fullName>Dr.</fullName>
                </value>
                <value>
                    <fullName>DrSc.</fullName>
                </value>
                <value>
                    <fullName>DSc.</fullName>
                </value>
                <value>
                    <fullName>Ing.</fullName>
                </value>
                <value>
                    <fullName>Ing. arch.</fullName>
                </value>
                <value>
                    <fullName>JUDr.</fullName>
                </value>
                <value>
                    <fullName>MDDr.</fullName>
                </value>
                <value>
                    <fullName>MgA.</fullName>
                </value>
                <value>
                    <fullName>Mgr.</fullName>
                </value>
                <value>
                    <fullName>MSDr.</fullName>
                </value>
                <value>
                    <fullName>MUDr.</fullName>
                </value>
                <value>
                    <fullName>MVDr.</fullName>
                </value>
                <value>
                    <fullName>odb. as.</fullName>
                </value>
                <value>
                    <fullName>PaedDr.</fullName>
                </value>
                <value>
                    <fullName>Ph.D.</fullName>
                </value>
                <value>
                    <fullName>PharmDr.</fullName>
                </value>
                <value>
                    <fullName>PhDr.</fullName>
                </value>
                <value>
                    <fullName>PhMr.</fullName>
                </value>
                <value>
                    <fullName>prof.</fullName>
                </value>
                <value>
                    <fullName>RCDr.</fullName>
                </value>
                <value>
                    <fullName>RNDr.</fullName>
                </value>
                <value>
                    <fullName>RSDr.</fullName>
                </value>
                <value>
                    <fullName>RTDr.</fullName>
                </value>
                <value>
                    <fullName>Th.D.</fullName>
                </value>
                <value>
                    <fullName>ThDr.</fullName>
                </value>
                <value>
                    <fullName>ThLic.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Acceptor__c.object
<CustomObject>
    <fields>
        <fullName>ER_AID_Authorization__c</fullName>
        <label>AID Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_AID_Clearing__c</fullName>
        <label>AID Clearing</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner:User.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Last_date_of_Sync__c</fullName>
        <label>Last date of Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ER_MCC_Authorization__c</fullName>
        <label>MCC Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MCC_Clearing__c</fullName>
        <label>MCC Clearing</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID_Authorization__c</fullName>
        <label>MID Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID_Clearing__c</fullName>
        <label>MID Clearing</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>ER_Store__c</referenceTo>
        <relationshipLabel>Acceptors</relationshipLabel>
        <relationshipName>Acceptors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_TID_Authorization__c</fullName>
        <externalId>true</externalId>
        <label>TID Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_TID_Clearing__c</fullName>
        <label>TID Clearing</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Acceptor</label>
    <nameField>
        <label>Acceptor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acceptors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner:User.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_City__c</fullName>
        <label>Billing City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.ER_Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Creation_date_in_OS__c</fullName>
        <description>Use as a reference for EDG data creation</description>
        <label>Creation date in OS</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ER_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Zip_Code__c</fullName>
        <label>Billing Zip Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Store__c.object
<CustomObject>
    <fields>
        <fullName>ER_Creation_Date_In_OS__c</fullName>
        <description>Used as a reference for EDG data creation</description>
        <label>Creation Date In OS</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ER_Last_Date_Of_Sync__c</fullName>
        <label>Last Date Of Sync</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ER_Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Brand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner:User.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.ER_Merchant__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ER_Do_not_publish__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Do not publish</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_E_Shop__c</fullName>
        <defaultValue>false</defaultValue>
        <label>E-Shop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Merchant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ER_Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZ_Store_reference__c</fullName>
        <label>Store reference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/ER_Brand.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>McDonald&apos;s</fullName>
    </customValue>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>Tim Hortons</fullName>
    </customValue>
    <customValue>
        <fullName>KFC</fullName>
    </customValue>
    <customValue>
        <fullName>Pizza Hut</fullName>
    </customValue>
    <customValue>
        <fullName>Taco Bell</fullName>
    </customValue>
    <customValue>
        <fullName>Domino&apos;s Pizza</fullName>
    </customValue>
    <customValue>
        <fullName>Starbucks</fullName>
    </customValue>
    <customValue>
        <fullName>Subway</fullName>
    </customValue>
    <customValue>
        <fullName>Carrefour</fullName>
    </customValue>
    <customValue>
        <fullName>Carrefour Market</fullName>
    </customValue>
    <customValue>
        <fullName>Carrefour Express</fullName>
    </customValue>
    <customValue>
        <fullName>Carrefour Bio</fullName>
    </customValue>
    <customValue>
        <fullName>EESS</fullName>
    </customValue>
    <customValue>
        <fullName>Carrefour Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Bon App!</fullName>
    </customValue>
    <customValue>
        <fullName>Carrefour VoyaDEs</fullName>
    </customValue>
    <customValue>
        <fullName>Carrefour Bank</fullName>
    </customValue>
    <customValue>
        <fullName>Carrefour.fr</fullName>
    </customValue>
    <customValue>
        <fullName>Lidl</fullName>
    </customValue>
    <customValue>
        <fullName>Kaufland</fullName>
    </customValue>
    <customValue>
        <fullName>Aldi</fullName>
    </customValue>
    <customValue>
        <fullName>Delhaize</fullName>
    </customValue>
    <customValue>
        <fullName>Albert Heijn</fullName>
    </customValue>
    <customValue>
        <fullName>Bol.com</fullName>
    </customValue>
    <customValue>
        <fullName>Albert</fullName>
    </customValue>
    <customValue>
        <fullName>AB</fullName>
    </customValue>
    <customValue>
        <fullName>ENA</fullName>
    </customValue>
    <customValue>
        <fullName>Pingo Doce</fullName>
    </customValue>
    <customValue>
        <fullName>Mega Image</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WSCZ01_SynchronizeStoreWS.cls
public class WSCZ01_SynchronizeStoreWS {
    
/*
    public static Boolean alreadyExecutedAcceptor = false;
    
    public static final String xp_salesforce_endpoint = System.Label.LAB_SF_EndpointEDG_WS;
    public static final String xp_salesforce_clientId = System.Label.LAB_SF_Client_Id_WS;
    public static final String xp_salesforce_requester = System.Label.LAB_SF_Requester_WS;
    
    public static ER_Store__c store = new ER_Store__c();
    
    
    public static void updateAddStoreFuture(ID storeId) {
        updateAddStore(storeId);
    }
    

    public static String updateAddStore(ID storeId) {
         
        store = [SELECT Id,ER_Business_Unit__c, ER_Merchant__c, Name,ER_Contact__c, ER_Street__c, ER_City__c, ER_Zip_Code__c, ER_Creation_Date_In_OS__c, ER_Financial_Center__c, ER_Financial_Center__r.ER_Creation_date_in_OS__c , ER_Last_Date_Of_Sync__c, ER_Contact__r.Fax, CZ_Store_reference__c,
                 ER_Contact__r.Email, ER_Contact__r.Phone, ER_Contact__r.MobilePhone, ER_Contact__r.FirstName, ER_Contact__r.LastName, ER_Contact__r.Salutation, CreatedDate, ER_Brand__c, ER_E_Shop__c, 
                 ER_Contact__r.MailingStreet, ER_Contact__r.MailingCity, ER_Contact__r.MailingPostalCode, ER_Contact__r.MailingCountry, ER_Contact__r.MailingLatitude, ER_Description__c, ER_Do_not_publish__c,
                 ER_Contact__r.MailingLongitude, ER_Contact__r.ER_Business_Unit_2__c, ER_Contact__r.CZ_AcademicTitle__c, (SELECT id, Name, ER_MID_Authorization__c , ER_AID_Authorization__c , ER_MCC_Authorization__c , 
                                                  ER_TID_Authorization__c, ER_TID_Clearing__c, ER_MID_Clearing__c , ER_AID_Clearing__c , ER_MCC_Clearing__c , 
                                                  ER_Card_Operational_System_ID__c, ER_Business_Unit__c FROM Acceptors__r) FROM ER_Store__c WHERE Id = :storeId];
            
          
        
        Map<String, String> EdgMatrixError = WSHU02_SynchronizeMerchantWS.getEDGMatrices();
        
        System.debug('--- Which is related to the following financial center ? ' + store.ER_Financial_Center__c);    
        
        ER_Financial_Center__c theInvC = [Select id, ER_Creation_date_in_OS__c, ER_Account_Name__c, ER_Paper_Operational_System_ID__c, ER_Card_Operational_System_ID__c from ER_Financial_Center__c where id = :store.ER_Financial_Center__c];
        
        String themerchant = store.ER_Merchant__c;
        
        System.debug('--- The financial center ? ' + theInvC);
        
        
        HttpResponse res;
        
            System.debug('--- WSCZ01_SynchronizeStoreWS.callWSAddStore start ');  
            res = WSCZ01_SynchronizeStoreWS.callWSAddStore(store, themerchant, true);
            System.debug('--- WSCZ01_SynchronizeStoreWS.callWSAddStore end ');
    
        System.debug('--- The status code returned was : ' +
                     res.getStatusCode() + ' ' + res.getStatus() + ' ' + res.getBody());
        
        List<APHU05_EDGMessageHandler> myResponse = APHU05_EDGMessageHandler.parse(res.getBody()); 
        
        System.debug('--- The final message is : ' + myResponse);
        
        
        if (myResponse[0].meta.status == 'succeeded') {
            System.debug('--- Is success : ');
            store.ER_Creation_Date_In_OS__c = DateTime.now();
            System.debug('--- ER_Creation_Date_In_OS__c Updated : ');
        }
        
        else {
            System.debug('--- Is Error : ');
            //acceptors[0].ER_Last_date_of_Sync__c = DateTime.now();
        }
        
        // Update the related account
        WSCZ01_SynchronizeStoreWS.alreadyExecutedAcceptor = true;
        System.debug('Stoooore :' + store);
        update store;
        System.debug('Stoooore Updated:' + store);
        return null;
    }
    
   
    public static HttpResponse callWSAddStore(ER_Store__c aStore, String aMerchant, Boolean isComplex) {
        String result;
        
        // Current date -- Ok	
        String currentDate = String.valueOf(datetime.now().formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\''));
        
        WSHU03_MerchantTemplateWS.Stores theStore = new WSHU03_MerchantTemplateWS.Stores(aStore);
        

        String body = JSON.serializePretty(theStore, true);
        System.debug('BODYYY'+ body);
        String afterblobToStringbis = APHU06_CryptoTokenGeneration.getEncodedbody(body);
        String hmacToken;
        HttpRequest req;
        
        if(store.ER_Business_Unit__c == 'CZ'){
             System.debug('BUUUU');
            // get the HmacToken to be send
            hmacToken = APHU06_CryptoTokenGeneration.getHmacToken('/merchants/ds.merchant.technical_id-' + aMerchant
                                                                  + '/stores',afterblobToStringbis, currentDate);
                                                                       
            req = APHU06_CryptoTokenGeneration.getHttpRequest('/merchants/ds.merchant.technical_id-' + aMerchant
                                                              + '/stores','POST', hmacToken, currentDate, afterblobToStringbis);  
        } 
        
 
        Http h = new Http();
        
        
        HttpResponse res;
        res = h.send(req);
        
        return  res;
    }
    
    
 */
    
}