src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IT_Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_ControlUpdateTrigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>IT_ControlTreiggerUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ControlTreiggerUpdate</label>
        <type>Checkbox</type>
    </fields>
    <label>ControlUpdateTrigger</label>
</CustomObject>

src/classes/WSIT06_Document_Test.cls
@istest
public class WSIT06_Document_Test {
    @isTest static void DocumentUpsertError() {
        IT_ControlUpdateTrigger__c settings = IT_ControlUpdateTrigger__c.getOrgDefaults();
        settings.IT_ControlTreiggerUpdate__c = true;
        insert settings;
        try{
            RestRequest request = new RestRequest();
            RestResponse res = new RestResponse();
            request.requestUri = '/services/apexrest/ac_document/';
            request.httpMethod = 'PUT';
            request.addHeader('Content-Type', 'application/json');
            request.requestBody = Blob.valueOf('{ "IT_Document": [ { "IT_Client_Code": "004311", "IT_Document_Protocol": "007432/20072006", "IT_Document_Progressive": 34330, "IT_Document_Type": "002", "IT_Registration_Date": "2010-12-20", "IT_Scan_Date": "2010-12-30", "IT_Barcode": "barCode", "IT_Framework_Barcode": null, "IT_PDF_File": "TGEgdml0YSDDqCBjb21lIHVuYSBzY2F0b2xhIGRpIGNpb2Njb2xhdGluaSwgbm9uIHNhbWkgcXVlbGxvIGNoZSB0aSBjYXBpdGVyw6AuCkNpdC4=", "IT_Send_Email": null, "IT_Email": null, "IT_Email_Sending_Date": null, "IT_Barcode_Warrant": null, "IT_Service": null, "IT_Service_2": null, "IT_Barcode_2": null, "IT_Service_3": null, "IT_Barcode_3": null, "IT_136_PDF_File": null, "IT_136_Send_Email": null, "IT_136_Email_Address": null, "IT_136_Email_Sending_Data": null, "IT_136_User_Sender": null, "IT_AC_User": null } ] }');
            RestContext.request = request;
            RestContext.response= res;
            WSIT06_Document.AnagraficaClientiUpsert(); 
        }catch(Exception ecc){
            System.debug('populateFinancialCenter: '+ecc.getMessage()+ ' at line: '+ecc.getLineNumber()+' stack trace: '+ecc.getStackTraceString());     
        }    
    }
    @isTest static void DocumentUpsert() {
        IT_ControlUpdateTrigger__c settings = IT_ControlUpdateTrigger__c.getOrgDefaults();
        settings.IT_ControlTreiggerUpdate__c = true;
        insert settings;
        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        accountTest.ER_VAT_Number__c = '02554698475';
        insert accountTest;
        Contact contactTest = APIT14_DataFactory.create_Contact(accountTest.Id);
        contactTest.IT_Code__c = 'StringString';
        insert contactTest;
        ER_Financial_Center__c FinancialTest = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest.ER_Card_Operational_System_ID__c = 'Tes2w';
        FinancialTest.ER_Type__c = 'Client'; 
        FinancialTest.IT_Financial_Center__c = '004311';
        insert FinancialTest;
        Contract contractTest = APIT14_DataFactory.create_Contract(accountTest.Id);
        contractTest.IT_Financial_center__c = FinancialTest.Id;
        contractTest.IT_Contract_Number__c = '5555/6666';
        insert contractTest;
        Attachment attach = new Attachment();   	
    	attach.Name='Unit Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=contractTest.id;
        insert attach;
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri = '/services/apexrest/ac_document/';
        request.httpMethod = 'PUT';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf('{ "IT_Document": [ { "IT_Client_Code": "004311", "IT_Document_Protocol": "007432/20072006", "IT_Document_Progressive": 34330, "IT_Document_Type": "002", "IT_Registration_Date": "2010-12-20", "IT_Scan_Date": "2010-12-30", "IT_Barcode": "barCode", "IT_Framework_Barcode": null, "IT_PDF_File": "TGEgdml0YSDDqCBjb21lIHVuYSBzY2F0b2xhIGRpIGNpb2Njb2xhdGluaSwgbm9uIHNhbWkgcXVlbGxvIGNoZSB0aSBjYXBpdGVyw6AuCkNpdC4=", "IT_Send_Email": null, "IT_Email": null, "IT_Email_Sending_Date": null, "IT_Barcode_Warrant": null, "IT_Service": null, "IT_Service_2": null, "IT_Barcode_2": null, "IT_Service_3": null, "IT_Barcode_3": null, "IT_136_PDF_File": null, "IT_136_Send_Email": null, "IT_136_Email_Address": null, "IT_136_Email_Sending_Data": null, "IT_136_User_Sender": null, "IT_AC_User": null } ] }');
        RestContext.request = request;
        RestContext.response= res;
        WSIT06_Document.AnagraficaClientiUpsert();  
    }

}