src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_BUPicklist__c</fullName>
        <defaultValue>$User.ER_BUText__c</defaultValue>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BUPicklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ER_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Legal_Form__c</fullName>
        <description>Legal form of the company</description>
        <label>Legal Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Other_Fiscal_ID__c</fullName>
        <label>Other Fiscal ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Registration_Number__c</fullName>
        <label>Company Registration Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Company_Type__c</fullName>
        <label>Company Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Institution</fullName>
                </value>
                <value>
                    <fullName>Private (work for Institution)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Fiscal_Code__c</fullName>
        <label>Fiscal Code</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Legal_Form__c</fullName>
        <label>Legal Form</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Legal_Form</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IT_Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/ER_Industry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Agriculture</fullName>
    </customValue>
    <customValue>
        <fullName>Apparel</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Biotechnology</fullName>
    </customValue>
    <customValue>
        <fullName>Chemicals</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Construction</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>Education</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Energy</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Environmental</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Food &amp; Beverage</fullName>
    </customValue>
    <customValue>
        <fullName>Furniture</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Station</fullName>
    </customValue>
    <customValue>
        <fullName>Government</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare</fullName>
    </customValue>
    <customValue>
        <fullName>Hospitality</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Lottery</fullName>
    </customValue>
    <customValue>
        <fullName>Machinery</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing and advertising agencies</fullName>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
    </customValue>
    <customValue>
        <fullName>Mining</fullName>
    </customValue>
    <masterLabel>Industry</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/APIT00_Cruscotto_Marketing_Test.cls
@IsTest
public with sharing class APIT00_Cruscotto_Marketing_Test {

	@testSetup
	static void testSetup() {

		Campaign campaign = new Campaign(Name = 'Campaign Test');
		insert campaign;

		Account account = APIT14_DataFactory.create_BusinessAccount();
        account.ER_VAT_Number__c   = '02824320176';
        account.IT_Fiscal_Code__c  = '01014660417';
        account.IT_Company_Type__c = 'Private';
        account.ER_Registration_Number__c = 'ER_Registration_Number__c';
        account.IT_Legal_Form__c   = 'ASS';
        account.IT_Industry__c     = '106';
        account.ER_BUPicklist__c  = 'IT';
        account.Phone = '3336574564';
        account.ER_Legal_Form__c = 'LegalForm';
        account.ER_Industry__c ='Energy';
        account.ER_Other_Fiscal_ID__c = '01014660417';
        account.BillingStreet = 'Billing';
        account.BillingCity = 'Billing';
        account.BillingState = 'Billing';
        account.BillingPostalCode = 'Billing';
        account.BillingCountry  = 'Billing';
        account.NumberOfEmployees = 50;
		insert account;

		Contact contact = APIT14_DataFactory.create_Contact(account.Id);
		contact.IT_Code__c = 'StringString';
		insert contact;

		CampaignMember campaignMember = new CampaignMember(
			CampaignId = campaign.Id, 
			ContactId = contact.Id, 
			IT_Account__c = account.Id,
			IT_User__c = UserInfo.getUserId()
		);
		
		insert campaignMember;
	}

	@IsTest
	public static void checkMethod(){
		List<APIT00_Cruscotto_Marketing.CampaingResponse> campaigns = APIT00_Cruscotto_Marketing.GetCampaignList();
	
        System.assertEquals(1, campaigns.size(), 'Campaigns');
        
		if(campaigns.size() > 0){
			APIT00_Cruscotto_Marketing.CampaingResponse campaign = campaigns.get(0);

			APIT00_Cruscotto_Marketing.CampaignMemberResponse campaignMembers = APIT00_Cruscotto_Marketing.getCampaignContacts(campaign.recordId);
			System.assertEquals(1, campaignMembers.contacts.size(), 'Campaign Member');
		}
		
	}

    
}