src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IT_Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Circuit_Code__c</fullName>
        <externalId>true</externalId>
        <label>Circuit Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Service__c</fullName>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Service</valueSetName>
        </valueSet>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BAIT02_BatchFinancialCenterChilds_Test.cls
@isTest
public class BAIT02_BatchFinancialCenterChilds_Test {
    @isTest
    static void batchFinancialCenterChilds(){
        List<ER_Financial_Center__c> FCList = new List<ER_Financial_Center__c>();
        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        accountTest.ER_VAT_Number__c = '02554698475';
        insert accountTest;
        Contact contactTest = APIT14_DataFactory.create_Contact(accountTest.Id);
        contactTest.IT_Code__c = 'StringString';
        insert contactTest;
        ER_Financial_Center__c FinancialTest = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest.ER_Card_Operational_System_ID__c = 'Tes2w';
        FinancialTest.ER_Type__c = 'Client'; 
        FinancialTest.IT_Financial_Center__c = '445566';
        FinancialTest.IT_Circuit_Code__c = 'CI5566';
        FinancialTest.IT_Service__c = '1B';
        FCList.add(FinancialTest);
        ER_Financial_Center__c FinancialTest2 = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest2.ER_Card_Operational_System_ID__c = 'Tes3w';
        FinancialTest2.ER_Type__c = 'Client'; 
        FinancialTest2.IT_Financial_Center__c = '445568';
        FinancialTest2.IT_Circuit_Code__c = 'CI5566';
        FinancialTest2.IT_Service__c = '2X';
        FCList.add(FinancialTest2);
        insert FCList;
        
        BAIT02_BatchFinancialCenterChilds batchRun = new BAIT02_BatchFinancialCenterChilds();
        database.executebatch(batchRun,200);

    }
}