src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BUPicklist__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Suspect</fullName>
                </value>
                <value>
                    <fullName>No potential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Account_Address_Sync__c</fullName>
        <label>Account Address Sync</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Synchronized with Account legal address</fullName>
                    <default>true</default>
                    <label>Synchronized with Account legal address</label>
                </value>
                <value>
                    <fullName>Not Synchronized with Account legal address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/APER17_Contact_Management.cls
public class APER17_Contact_Management {
/*
----------------------------------------------------------------------
-- - Name          : APER17_Contact_Management
-- - Author        : OLA
-- - Description   : Contact Management, This class is used to group all the functionnality linked to the object Contact
--
-- Date         Name                Version     				Remarks
-- -----------  -----------         --------    ---------------------------------------
--  Aug-2019       OLA                1.0         			Initial version
---------------------------------------------------------------------------------------
*/
    
    public static void syncAddressFromAccount(Map<id,Account> accountMap) {
        
        List<Contact> contactToUpdate = new List<Contact>();
        
        for(Contact cont : [select id,accountId from Contact where accountId in : accountMap.keyset() and ER_Account_Address_Sync__c =: Label.LABS_SF_Account_SyncAddressContact and ER_Status__c !=: Label.LAB_SF_Contact_Inactive]){
            
            cont.MailingStreet = accountMap.get(cont.accountId).BillingStreet;
            cont.MailingPostalCode = accountMap.get(cont.accountId).BillingPostalCode;
            cont.MailingCity = accountMap.get(cont.accountId).BillingCity;
            cont.MailingCountry = accountMap.get(cont.accountId).BillingCountry;
            cont.MailingPostalCode = accountMap.get(cont.accountId).BillingPostalCode;
            
            contactToUpdate.add(cont);
        }
        if(!contactToUpdate.isEmpty()){
            
            System.debug('###APER17_Contact_Management syncAddressFromAccount contactToUpdate : '+contactToUpdate);
            update contactToUpdate;
        }
    }  
}