src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Company_Type__c</fullName>
        <label>Company Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Institution</fullName>
                </value>
                <value>
                    <fullName>Private (work for Institution)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Fiscal_Code__c</fullName>
        <label>Fiscal Code</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Industry__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Industry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Legal_Form__c</fullName>
        <label>Legal Form</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Legal_Form</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IT_Welfare_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Welfare Project</label>
        <referenceTo>IT_Welfare_Project__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_Benefit__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/IT_Benefit__c/fields/IT_Benefit__c.field-meta.xml
<CustomField>
    <fullName>IT_Benefit__c</fullName>
    <label>Benefit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>IT_Macro_Benefit__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medical Fees</fullName>
            </value>
            <value>
                <fullName>School Fees</fullName>
            </value>
            <value>
                <fullName>Family Care</fullName>
            </value>
            <value>
                <fullName>Public Transport</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Paper Top Premium</fullName>
            </value>
            <value>
                <fullName>Printable Top Premium</fullName>
            </value>
            <value>
                <fullName>Paper Selection</fullName>
            </value>
            <value>
                <fullName>Printable Selection</fullName>
            </value>
            <value>
                <fullName>Ticket Welfare1</fullName>
                <label>Ticket Welfare - Packages (Portale Beneficiari)</label>
            </value>
            <value>
                <fullName>Ticket Welfare - Integrated (Portale Titolari)</fullName>
            </value>
            <value>
                <fullName>Ticket Transport (ATM)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Amazon</fullName>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Monetization</fullName>
            </value>
            <value>
                <fullName>Online Purchases (NO Amazon)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IT_Benefit__c/fields/IT_Fund_Name_1__c.field-meta.xml
<CustomField>
    <fullName>IT_Fund_Name_1__c</fullName>
    <label>Fund Name 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IT_Benefit__c/fields/IT_Macro_Benefit__c.field-meta.xml
<CustomField>
    <fullName>IT_Macro_Benefit__c</fullName>
    <label>Macro Benefit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reimbursement</fullName>
            </value>
            <value>
                <fullName>Fund</fullName>
            </value>
            <value>
                <fullName>Ticket Compliments</fullName>
            </value>
            <value>
                <fullName>Ticket Welfare</fullName>
            </value>
            <value>
                <fullName>Ticket Transport</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IT_Benefit__c/fields/IT_Plan__c.field-meta.xml
<CustomField>
    <fullName>IT_Plan__c</fullName>
    <label>Plan</label>
    <referenceTo>IT_Plan__c</referenceTo>
    <relationshipName>IT_Plan_Component</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/IT_Plan__c.object
<CustomObject>
    <fields>
        <fullName>IT_Welfare_Project__c</fullName>
        <label>Welfare Project</label>
        <referenceTo>IT_Welfare_Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan</label>

    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IT_Welfare_Project__c.object
<CustomObject>
    <fields>
        <fullName>IT_Benefit__c</fullName>
        <label>Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>IT_Macro_Benefit__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Medical Fees</fullName>
                </value>
                <value>
                    <fullName>School Fees</fullName>
                </value>
                <value>
                    <fullName>Family Care</fullName>
                </value>
                <value>
                    <fullName>Public Transport</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Paper Top Premium</fullName>
                </value>
                <value>
                    <fullName>Printable Top Premium</fullName>
                </value>
                <value>
                    <fullName>Paper Selection</fullName>
                </value>
                <value>
                    <fullName>Printable Selection</fullName>
                </value>
                <value>
                    <fullName>Ticket Welfare - Packages (Portale Beneficiari)</fullName>
                </value>
                <value>
                    <fullName>Ticket Welfare - Integrated (Portale Titolari)</fullName>
                </value>
                <value>
                    <fullName>Ticket Transport (ATM)</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Amazon</fullName>
                </value>
                <value>
                    <fullName>Loans</fullName>
                </value>
                <value>
                    <fullName>Monetization</fullName>
                </value>
                <value>
                    <fullName>Online Purchases (NO Amazon)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Macro_Benefit__c</fullName>
        <label>Macro Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Reimbursement</fullName>
                </value>
                <value>
                    <fullName>Fund</fullName>
                </value>
                <value>
                    <fullName>Ticket Compliments</fullName>
                </value>
                <value>
                    <fullName>Ticket Welfare</fullName>
                </value>
                <value>
                    <fullName>Ticket Transport</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Welfare Project</label>
    <nameField>
        <label>Welfare Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Welfare Project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APIT30_IntegrationPagesControllerTest.cls
@isTest

public class APIT30_IntegrationPagesControllerTest {
    @testSetup static void setup() {
        
    }
    
    @isTest 
    static void testSubmit() {
        //list Contacts
        List<Contact> contacts= new List<Contact>{
            new Contact(Phone='77125216536',Email='testMail@gmail.com',FirstName='Test', LastName='Contact')
                };
                    insert contacts;
        
        //list Accounts
        List<Account> accounts= new List<Account>{
            new Account(Name='test safona', IT_Company_Type__c='private', IT_Industry__c='10', ER_VAT_Number__c='470550013' , IT_Fiscal_Code__c='470550013', IT_Legal_Form__c='AG')
                };
                    insert accounts;
        
        //list IT_Welfare_Project IT_Welfare_Project__c
        List<IT_Welfare_Project__c> welfareProjects= new List<IT_Welfare_Project__c>{
            new IT_Welfare_Project__c(Name='test Welfare')
                };
                    insert welfareProjects;
        IT_Plan__c plan = new IT_Plan__c(Name='test plan',IT_Welfare_Project__c = welfareProjects[0].Id);
        insert plan;
        //list case 
        List<case> cases = new List<case> {
            new Case(AccountId=accounts[0].Id,ContactId=contacts[0].Id, IT_Welfare_Project__c=welfareProjects[0].Id)
                };
                    insert cases;
        //plan 
        
        
        
        /*list benefit
        List<IT_Benefit__c> lbenefit = new List<IT_Benefit__c> {
          new IT_Benefit__c ( IT_Macro_Benefit__c = 'Reimbursement', IT_Benefit__c = 'School Fees'),
          new IT_Benefit__c(IT_Macro_Benefit__c = 'Reimbursement', IT_Benefit__c = 'Family Care'),
          new IT_Benefit__c(IT_Macro_Benefit__c = 'Reimbursement', IT_Benefit__c = 'Public Transport'),
          new IT_Benefit__c(IT_Macro_Benefit__c = 'Fund', IT_Benefit__c = 'Insurance', IT_Fund_Name_1__c='test')
              };
                  insert lbenefit;
        
        */
         
       
            
        Case cse= [select CaseNumber from Case limit 1 ];
        system.debug('cases '+cse);   
        //data reference page
        PageReference pageRef = Page.VFIT30_IntegrationPages_Form;
        test.setCurrentPageReference(pageRef);
        pageRef.getParameters().put('caseNumber',cse.CaseNumber);
        
        Test.setMock(HttpCalloutMock.class, new MdaForm());
        APIT30_IntegrationPagesController mdaform = new APIT30_IntegrationPagesController();
        //mdaform.piano = plan;
        mdaform.selectedBenefit = 0;
        mdaform.selectedContact = 0;// 
        mdaform.pdfHtml = '<p>html content</p>';
        mdaform.benefitDaAttivare = new List<String>{'cassa','istruzione','assistenza','trasporto','previdenza','compliments','other'};
        mdaform.contact = new Contact(LastName='contact',FirstName='test',Phone='77125216536',Email='test@gmail.it');
        Test.startTest();
        mdaform.showReferenteSelected();
        mdaform.displayPdf();
        mdaform.savePdfAttachment();
        mdaform.deleteRows();
        mdaform.addContact();
        mdaform.addContact();
        mdaform.deleteContacts();
        mdaform.addFunding();
        mdaform.savePlan();
        mdaform.insertRefCassaSanitaria(new Contact(LastName='contact',FirstName='test',Phone='77125216536',Email='test@gmail.it'));
        mdaform.insertRefCassaSanitaria(new Contact(LastName='contact',FirstName='test',Phone='77125216536'));
        Test.stopTest();
    
    }
    
    @isTest
    static void PassParametersTest(){
        APIT30_IntegrationPagesController mdaform = new APIT30_IntegrationPagesController();
        APIT30_IntegrationPagesController mdaform2 = new APIT30_IntegrationPagesController();
        mdaform2.addFunding();
        mdaform2.selectedFunding = 0;
        Test.startTest();
        mdaform.PassParameters();
        mdaform2.PassParameters();
        Test.stopTest();
    }
    
    @isTest
    static void listMethodsTest(){
        APIT30_IntegrationPagesController mdaform = new APIT30_IntegrationPagesController();
        mdaform.selectedFunding = 0;
        mdaform.indexToDelete = 0;
        //mdaform.societaObject = new SocietaObject('test nome','test indrizzo', 'pec', 'test@test.it', 0);
        Test.startTest();
        mdaform.showReferente = 'unica';
        mdaform.addToSocietaList();
        mdaform.deleteSocietaToList();
        mdaform.showReferente = 'referente';
        mdaform.addToSocietaList();
        mdaform.addToSocietaList();
        mdaform.deleteSocietaToList();
        mdaform.addToSedeList();
        mdaform.addToSedeList();
        mdaform.deleteSedeToList();
        mdaform.addFunding();
        mdaform.addFunding();
        mdaform.getReferenteOptions();
        mdaform.getSeparataOptions();
        mdaform.getBillingOptions();
        mdaform.getReferenteOptions();
        mdaform.deleteRows();
        mdaform.addContact();
        mdaform.addContact();
        mdaform.addToUnicaList();
        mdaform.deleteUnicaToList();
        Test.stopTest();
    }
    
    @isTest
    static void PassParametersTest2(){
        APIT30_IntegrationPagesController mdaform = new APIT30_IntegrationPagesController();
        Test.startTest();
        mdaform.PassParameters();
        Test.stopTest();
    }
    
    public class MdaForm implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/java');
            response.setBody('{ "meta": {"messages":[],"status":"succeeded"},"data":[{"abbreviation":"AG", "chief_town_istat_code":"084001", "istat_code":"084", "name":"AGRIGENTO", "name_display":"Agrigento", "province_ref":"38000000022", "region_ref":"38000000020"}]}');
            response.setStatusCode(200);
            return response; 
        }
    }
}