src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For Beneficiary, reference the Client on the beneficary</description>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Users</relationshipLabel>
        <relationshipName>UserClient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>ER_Employee__c</referenceTo>
        <relationshipLabel>Individual</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>ER_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets (Client)</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>ER_Employee__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ER_Asset_Record_Type</fullName>
        <active>true</active>
        <label>Asset</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Number__c</fullName>
        <label>Card Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>ER_Employee__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>ER_User_Case_RT</fullName>
        <active>true</active>
        <businessProcess>User Support</businessProcess>
        <description>Record Type for the User Case</description>
        <label>ER User Case RT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Employee__c.object
<CustomObject>
    <fields>
        <fullName>ER_Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/APER08_Case_Management_Test.cls
/**
* @author Oussama LASFAR
* @date 26/09/2018 (dd/mm/yyyy)
* @description test class to cover the case trigger before update
*/
@isTest
public class APER08_Case_Management_Test {
    @testSetup
    static void testSetup() {
        Account newCompany = APER07_UtilityTestMethod.getCompany('VFCER01_Asset_Transactions_Balance_Test');
        insert newCompany;
        
        ER_Employee__c newEmployee = APER07_UtilityTestMethod.getEmployee();
        newEmployee.ER_Client__c = newCompany.id;
        insert newEmployee;
        
        Product2 newProduct = APER07_UtilityTestMethod.getProduct('TSC_P');
        insert newProduct;
        
        Asset newAsset = APER07_UtilityTestMethod.getAsset('2801001840','ER_Asset_Record_Type',Label.LAB_SF_ASSET_Type);
        newAsset.ER_Employee__c = newEmployee.id;
        newAsset.AccountId = newCompany.id;
        newAsset.Product2Id = newProduct.id;
        insert newAsset;
        
        Entitlement ent = new Entitlement();
        ent.Name = 'TestEntitlement';
        ent.AccountId = newCompany.id;
        List<SlaProcess> slaInst = [SELECT Id,name,isactive From SlaProcess limit 1];
        if(!slaInst.isEmpty()){
            
            ent.SlaProcessId = [SELECT Id,name,isactive From SlaProcess limit 1].id;
        }
        insert ent;
        
        Case testCase = new Case();
        testCase.Origin = Label.LABS_SF_Case_Origin_Web;
        testCase.Status= Label.LAB_SF_Case_inProgress;
        testCase.ER_Card_Number__c= '2801001840';
        testCase.recordtypeid = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ER_User_Case_RT').getRecordTypeId();
        insert testCase;        
    }
    static testMethod void completeMilestone() {
        List<Case> caseinst = [select id from Case limit 1];
        if(!caseinst.isEmpty()){
            caseinst[0].Status=Label.LAB_SF_Case_resolved;
            update caseinst[0];
            caseinst[0].Status=Label.LAB_SF_Case_feedbackSent;
            update caseinst[0];
        }
    }
    
}