src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ER_Acceptor__c.object
<CustomObject>
    <fields>
        <fullName>ER_AID_Authorization__c</fullName>
        <label>AID Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_AID_Clearing__c</fullName>
        <label>AID Clearing</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_AID__c</fullName>
        <label>AID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MCC_Authorization__c</fullName>
        <label>MCC Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MCC_Clearing__c</fullName>
        <label>MCC Clearing</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID_AID__c</fullName>
        <label>MID_AID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID_Authorization__c</fullName>
        <label>MID Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID_Clearing__c</fullName>
        <label>MID Clearing</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID__c</fullName>
        <label>MID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>ER_Store__c</referenceTo>
        <relationshipLabel>Acceptors</relationshipLabel>
        <relationshipName>Acceptors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_SubMID_Authorization__c</fullName>
        <label>Sub MID Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Sub_MID_Clearing__c</fullName>
        <label>Sub MID Clearing</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_TID_Authorization__c</fullName>
        <externalId>true</externalId>
        <label>TID Authorization</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_TID_Clearing__c</fullName>
        <label>TID Clearing</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Acceptor</label>
    <nameField>
        <label>Acceptor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acceptors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_City__c</fullName>
        <label>Billing City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Country__c</fullName>
        <label>Billing Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Invoicing_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoicing Site ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Zip_Code__c</fullName>
        <label>Billing Zip Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Store__c.object
<CustomObject>
    <fields>
        <fullName>ER_City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Invoicing_site__c</fullName>
        <formula>ER_Financial_Center__r.ER_Invoicing_Site__c</formula>
        <label>Invoicing site ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Merchant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Merchant</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stores</relationshipLabel>
        <relationshipName>Stores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bakery</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pizzeria</fullName>
                </value>
                <value>
                    <fullName>Restaurant</fullName>
                </value>
                <value>
                    <fullName>Snack</fullName>
                </value>
                <value>
                    <fullName>Hypermarket</fullName>
                </value>
                <value>
                    <fullName>Supermarket</fullName>
                </value>
                <value>
                    <fullName>Convenience stores</fullName>
                </value>
                <value>
                    <fullName>Fast food</fullName>
                </value>
                <value>
                    <fullName>Cantine</fullName>
                </value>
                <value>
                    <fullName>Gas stations</fullName>
                </value>
                <value>
                    <fullName>Grocery</fullName>
                </value>
                <value>
                    <fullName>Discounter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ER_AID_Authorization__c</fullName>
        <label>AID Authorization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_AID_Clearing__c</fullName>
        <label>AID Clearing</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_AID__c</fullName>
        <label>AID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Legal_City__c</fullName>
        <label>Legal City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Legal_Country__c</fullName>
        <label>Legal Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Legal_Street__c</fullName>
        <label>Legal Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Legal_Zip_Code__c</fullName>
        <label>Legal Zip Code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MCC_Authorization__c</fullName>
        <label>MCC Authorization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MCC_Clearing__c</fullName>
        <label>MCC Clearing</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID_AID__c</fullName>
        <label>MID_AID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_MID_Authorization__c</fullName>
        <label>MID Authorization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID_Clearing__c</fullName>
        <label>MID Clearing</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_MID__c</fullName>
        <label>MID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Store_Name__c</fullName>
        <label>Store Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Sub_MID_Authorization__c</fullName>
        <label>Sub MID Authorization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Sub_MID_Clearing__c</fullName>
        <label>Sub MID Clearing</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_TID_Authorization__c</fullName>
        <label>TID Authorization</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_TID_Clearing__c</fullName>
        <label>TID Clearing</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Terminal__c</fullName>
        <label>Terminal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Don&apos;t know</fullName>
                    <default>true</default>
                    <label>Don&apos;t know</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Legal_State_Province__c</fullName>
        <label>Legal State/Province</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>ER_Client_Lead_RT</fullName>
        <active>true</active>
        <businessProcess>Client Lead Process</businessProcess>
        <label>Client Lead</label>
    </recordTypes>
    <recordTypes>
        <fullName>ER_Merchant_Lead_RT</fullName>
        <active>true</active>
        <businessProcess>Merchant Lead Process</businessProcess>
        <label>Merchant Lead</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/APER03_Lead_CreateFinancialCenter.cls
public with sharing class APER03_Lead_CreateFinancialCenter {
/*
----------------------------------------------------------------------
-- - Name          : APER03_Lead_CreateFinancialCenter
-- - Author        : AAB
-- - Description   : Process the Financial Center creation on lead conversion       
-- Maintenance History:
--
-- Date         Name                Version     Remarks 
-- -----------  -----------         --------    ---------------------------------------
-- 16-JUL-2018  AAB                 1.0         Initial version
-- 17-JUL-2018  AAB                 2.0         Add the related store creation
-- 29-APR-2019  OLA                 2.1         Add Financial center type condition
---------------------------------------------------------------------------------------
*/

public static void createFinancialCenter(List<Lead> listOflead) {
    List<ER_Financial_Center__c> financialC = new List<ER_Financial_Center__c>();
    List<ER_Store__c> listofStore = new List<ER_Store__c>();
    Database.SaveResult sr;
    Database.SaveResult sr1;
    String financialCenterType;

    APER05_DoNotRunTrigger donotRunTrigger = new  APER05_DoNotRunTrigger();
    donotRunTrigger.setDoNotRunTrigger();  

    for (Lead ld : listOflead) {

            //OLA Add New Conditions for Type. 29042019
            if(ld.recordTypeId == Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('ER_Merchant_Lead_RT').getRecordTypeId()){
                financialCenterType = Label.LABS_SF_FinancialCenter_Merchant;
                //////// Update the address of the account with the custom address of the lead
                Account AccConverted = new Account();
                AccConverted.Id = ld.ConvertedAccountId;
                AccConverted.BillingStreet = ld.ER_Legal_Street__c;
                AccConverted.BillingCity = ld.ER_Legal_City__c;
                AccConverted.BillingCountry = ld.ER_Legal_Country__c;
                AccConverted.BillingPostalCode = ld.ER_Legal_Zip_Code__c;
                AccConverted.BillingState = ld.ER_Legal_State_Province__c;
                update AccConverted;
                ////////
            }
            else if(ld.recordTypeId == Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('ER_Client_Lead_RT').getRecordTypeId()){
                financialCenterType = Label.LABS_SF_FinancialCenter_Client;
            }

            ER_Financial_Center__c myFinancialCenter = new ER_Financial_Center__c(Name = ld.Company,
             ER_Account_Name__c = ld.ConvertedAccountId,                         
             ER_Street__c = ld.Street,
             ER_City__c = ld.City,
             ER_Zip_Code__c = ld.PostalCode ,
             ER_Country__c = ld.Country,
             ER_Invoicing_Site__c = true,
             ER_Type__c = financialCenterType);
            
            
            // Insert the "Financial Center"
            sr = Database.insert(myFinancialCenter, false);
            
            ER_Store__c mystore = null;

            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('The batch has been successfully proceed. Financial Center ID: ' + sr.getId());
                
                if (myFinancialCenter.ER_Type__c == Label.LABS_SF_FinancialCenter_Merchant) {

                    mystore = new ER_Store__c(Name = ld.ER_Store_Name__c != null ? ld.ER_Store_Name__c : ld.Company,
                        ER_Merchant__c = ld.ConvertedAccountId,
                        ER_Financial_Center__c = myFinancialCenter.Id,
                        ER_Street__c = ld.Street,
                        ER_City__c = ld.City,
                        ER_Zip_Code__c = ld.PostalCode ,
                        ER_Country__c = ld.Country);

                    // Insert the "Financial Center"
                    sr1 = Database.insert(mystore, false);

                    System.debug('The batch has been successfully proceed. Store Center ID: ' + sr.getId() + mystore);
                     ER_Acceptor__c myAcceptor = null;

                    if (sr1.isSuccess() && ld.ER_Terminal__c == 'Yes') {

                        myAcceptor = new ER_Acceptor__c(Name = mystore.Name, ER_Store__c = mystore.Id,
                        ER_AID__c = ld.ER_AID__c,
                        ER_AID_Authorization__c = ld.ER_AID_Authorization__c,
                        ER_AID_Clearing__c = ld.ER_AID_Clearing__c,
                        ER_MCC_Authorization__c = ld.ER_MCC_Authorization__c,
                        ER_MCC_Clearing__c = ld.ER_MCC_Clearing__c, 
                        ER_MID__c = ld.ER_MID__c,
                        ER_MID_Authorization__c = ld.ER_MID_Authorization__c,
                        ER_MID_Clearing__c = ld.ER_MID_Clearing__c,
                        ER_MID_AID__c = ld.ER_MID_AID__c,
                        ER_SubMID_Authorization__c = ld.ER_Sub_MID_Authorization__c,
                        ER_Sub_MID_Clearing__c = ld.ER_Sub_MID_Clearing__c, 
                        ER_TID_Authorization__c = ld.ER_TID_Authorization__c,
                        ER_TID_Clearing__c = ld.ER_TID_Clearing__c
                        );

                        sr1 = Database.insert(myAcceptor, false);
                        myAcceptor = null; 
                    }

                }
            }
            
            myFinancialCenter = null;



            
        }
    }
}