src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IT_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
                <value>
                    <fullName>Merchant Client</fullName>
                </value>
                <value>
                    <fullName>Group Brand</fullName>
                </value>
                <value>
                    <fullName>Subsidiary Brand</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IT_Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IT_Type__c</fullName>
        <defaultValue>&quot;Ref&quot;</defaultValue>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cli</fullName>
                </value>
                <value>
                    <fullName>Attv</fullName>
                </value>
                <value>
                    <fullName>Vons</fullName>
                </value>
                <value>
                    <fullName>Ref</fullName>
                    <default>true</default>
                    <label>Ref</label>
                </value>
                <value>
                    <fullName>Soc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Delivery_Site__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Delivery Sites</relationshipLabel>
        <relationshipName>Delivery_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Delivery_AC__c</fullName>
        <label>Delivery AC</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Delivery Site</label>
    <nameField>
        <label>Delivery Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Distribution_Point__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/ER_Distribution_Point__c/fields/ER_Delivery_Site__c.field-meta.xml
<CustomField>
    <fullName>ER_Delivery_Site__c</fullName>
    <label>Delivery Site</label>
    <referenceTo>ER_Delivery_Site__c</referenceTo>
    <relationshipLabel>Distribution Points</relationshipLabel>
    <relationshipName>Distribution_Points</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_AC_Activity__c.field-meta.xml
<CustomField>
    <fullName>IT_AC_Activity__c</fullName>
    <label>AC Activity</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Financial_Center__c.field-meta.xml
<CustomField>
    <fullName>IT_Financial_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Center</label>
    <referenceTo>ER_Financial_Center__c</referenceTo>
    <relationshipLabel>Distribution Points</relationshipLabel>
    <relationshipName>Distribution_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_Contact_Detail__c.object
<CustomObject>
    <fields>
        <fullName>IT_Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Contact Details</relationshipLabel>
        <relationshipName>Contact_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Detail</label>
    <nameField>
        <label>Contact Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_ControlUpdateTrigger__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>IT_ControlTreiggerUpdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ControlTreiggerUpdate</label>
        <type>Checkbox</type>
    </fields>
    <label>ControlUpdateTrigger</label>
</CustomObject>

src/classes/WSIT05_ACContact_Test.cls
@istest
public class WSIT05_ACContact_Test {
    @isTest static void ContactUpsertError() {
        IT_ControlUpdateTrigger__c settings = IT_ControlUpdateTrigger__c.getOrgDefaults();
        settings.IT_ControlTreiggerUpdate__c = true;
        insert settings;
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri = '/services/apexrest/ac_contact/';
        request.httpMethod = 'PUT';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf('{ "IT_Contact":[ { "IT_Code":"", "LastName":"StringString", "FirstName":"StringString", "Phone":"StringString", "Fax":"StringString", "Email":"test.test@testtest.it", "IT_PEC":"test.test@testtest.it", "IT_Type":"Cli", "IT_Order_Making":true, "IT_Ticket_Receipts":true, "IT_Client_Billing_Recepits":true, "IT_AC_User":"StringString", "IT_Validity_Start_Date":"2019-01-01", "IT_Validity_End_Date":"2019-01-01", "IT_Contact_Association":[ { "IT_Code":"", "IT_Client_Code":"", "IT_Type":"Test1", "IT_Activity_AC":"lkjhg", "IT_Activity_SF":"test", "IT_Delivery_AC":"555666", "IT_Delivery_SF":32, "IT_Contact_Progressive":"15", "IT_Contact_Info":"", "IT_Apparatus_Type":"001DD", "IT_Order_Confirm_Address":true, "IT_Billing_Confirm_Address":true, "IT_Sut":true, "IT_Notifications":true, "IT_AC_User":"StringString" } ] } ] }');
        RestContext.request = request;
        RestContext.response= res;
        WSIT05_ACContact.AnagraficaClientiUpsert();  
    }
    @isTest static void ContactUpsert() {
        IT_ControlUpdateTrigger__c settings = IT_ControlUpdateTrigger__c.getOrgDefaults();
        settings.IT_ControlTreiggerUpdate__c = true;
        insert settings;

        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        insert accountTest;
        Contact contactTest2 = APIT14_DataFactory.create_Contact(accountTest.Id);
        contactTest2.IT_Code__c = 'StringSoc2';
        contactTest2.IT_Type__c = 'Soc';
        insert contactTest2;
        Contact contactTest = APIT14_DataFactory.create_Contact(accountTest.Id);
        contactTest.IT_Code__c = 'StringString';
        insert contactTest;
        IT_Contact_Detail__c contactDetailTest = APIT14_DataFactory.create_Contact_Detail(contactTest.Id);
        contactDetailTest.IT_Code__c = 'StringString';
        insert contactDetailTest;
        ER_Financial_Center__c FinancialTest = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest.ER_Card_Operational_System_ID__c = 'Tes2w';
        FinancialTest.ER_Type__c = 'Client'; 
        FinancialTest.IT_Financial_Center__c = '454256';
        insert FinancialTest;
        ER_Delivery_Site__c deliverysiteTest = APIT14_DataFactory.create_DeliverySite(FinancialTest.Id, accountTest.Id);
        deliverysiteTest.IT_Delivery_AC__c = '555666';
        insert deliverysiteTest;
        ER_Distribution_Point__c distributionPointTest = APIT14_DataFactory.create_DistributionPoint(FinancialTest.Id, deliverysiteTest.Id);
        distributionPointTest.IT_AC_Activity__c = 'lkjhg';
        insert distributionPointTest;

        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri = '/services/apexrest/ac_contact/';
        request.httpMethod = 'PUT';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf('{ "IT_Contact":[ { "IT_Code":"StringString", "LastName":"StringString", "FirstName":"StringString", "Phone":"StringString", "Fax":"StringString", "Email":"test.test@testtest.it", "IT_PEC":"test.test@testtest.it", "IT_Type":"Cli", "IT_Order_Making":true, "IT_Ticket_Receipts":true, "IT_Client_Billing_Recepits":true, "IT_AC_User":"StringString", "IT_Validity_Start_Date":"2019-01-01", "IT_Validity_End_Date":"2019-01-01", "IT_Contact_Association":[ { "IT_Code":"StringString", "IT_Client_Code":"454256", "IT_Type":"Test1", "IT_Activity_AC":"lkjhg", "IT_Activity_SF":"test", "IT_Delivery_AC":"555666", "IT_Delivery_SF":32, "IT_Contact_Progressive":"16", "IT_Contact_Info":"StringString", "IT_Apparatus_Type":"001", "IT_Order_Confirm_Address":true, "IT_Billing_Confirm_Address":true, "IT_Sut":true, "IT_Notifications":true, "IT_AC_User":"StringString" } ] } ] }');
        RestContext.request = request;
        RestContext.response= res;
        WSIT05_ACContact.AnagraficaClientiUpsert();  
    }
    @isTest static void ContactUpsertErrorField() {
        IT_ControlUpdateTrigger__c settings = IT_ControlUpdateTrigger__c.getOrgDefaults();
        settings.IT_ControlTreiggerUpdate__c = true;
        insert settings;

        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        insert accountTest;
        Contact contactTest = APIT14_DataFactory.create_Contact(accountTest.Id);
        insert contactTest;
        ER_Financial_Center__c FinancialTest = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest.ER_Card_Operational_System_ID__c = 'Tes2w';
        FinancialTest.ER_Type__c = 'Client'; 
        FinancialTest.IT_Financial_Center__c = '454256';
        insert FinancialTest;
        ER_Delivery_Site__c deliverysiteTest = APIT14_DataFactory.create_DeliverySite(FinancialTest.Id, accountTest.Id);
        deliverysiteTest.IT_Delivery_AC__c = '555666';
        insert deliverysiteTest;
        ER_Distribution_Point__c distributionPointTest = APIT14_DataFactory.create_DistributionPoint(FinancialTest.Id, deliverysiteTest.Id);
        distributionPointTest.IT_AC_Activity__c = 'lkjhg';
        insert distributionPointTest;

        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri = '/services/apexrest/ac_contact/';
        request.httpMethod = 'PUT';
        request.addHeader('Content-Type', 'application/json');
        request.requestBody = Blob.valueOf('{ "IT_Contact":[ { "IT_Code":"StringString", "LastName":"StringString", "FirstName":"StringString", "Phone":"StringString", "Fax":"StringString", "Email":"test.test@testtest.it", "IT_PEC":"test.test@testtest.it", "IT_Type":"Cli", "IT_Order_Making":true, "IT_Ticket_Receipts":true, "IT_Client_Billing_Recepits":true, "IT_AC_User":"StringString", "IT_Validity_Start_Date":"2019-01-01", "IT_Validity_End_Date":"2019-01-01", "IT_Contact_Association":[ { "IT_Code":"StringString", "IT_Client_Code":"454256", "IT_Type":"Test1", "IT_Activity_AC":"lkjhg", "IT_Activity_SF":"test", "IT_Delivery_AC":"555666", "IT_Delivery_SF":32, "IT_Contact_Progressive":"18", "IT_Contact_Info":"StringString", "IT_Apparatus_Type":"001M", "IT_Order_Confirm_Address":true, "IT_Billing_Confirm_Address":true, "IT_Sut":true, "IT_Notifications":true, "IT_AC_User":"StringString" } ] } ] }');
        RestContext.request = request;
        RestContext.response= res;
        WSIT05_ACContact.AnagraficaClientiUpsert();  
    }
}