src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ER_ContractLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>ER_Contract__r.ER_Business_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>ER_ContractLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Minimum_Fee__c</fullName>
        <label>Minimum Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ER_NeedApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Approval ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Percentage__c</fullName>
        <label>Percentage</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ER_Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billable Service</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>ContractLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Solution__c</fullName>
        <formula>ER_Product2__r.ER_Solution_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution</label>
        <type>Text</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Contract Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Product_Dependency__c.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <defaultValue>$User.ER_BUText__c</defaultValue>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Configuration__c</fullName>
        <label>Configuration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mandatory</fullName>
                </value>
                <value>
                    <fullName>Optional</fullName>
                </value>
                <value>
                    <fullName>Incompatible</fullName>
                </value>
                <value>
                    <fullName>AutoLink</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Controlling_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Controlling Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Dependent Products</relationshipLabel>
        <relationshipName>ER_Product_Dependencies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Dependent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Controller products</relationshipLabel>
        <relationshipName>ER_Product_Controllers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Dependency</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Product Dependency</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Dependencies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ER_AmendedFromContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amended From Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amended Opportunities</relationshipLabel>
        <relationshipName>AmendedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_AmendedFromOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amended From Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_BU_Picklist__c</fullName>
        <defaultValue>$User.ER_BUText__c</defaultValue>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_NeedApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Approval ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_IsAmended__c</fullName>
        <formula>OR(
            NOT(ISBLANK(ER_AmendedFromOpportunity__c)),
            NOT(ISBLANK(ER_AmendedFromContract__c))
            )
        </formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amended ?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ER_Minimum_Fee__c</fullName>
        <label>Minimum Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ER_NeedApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Approval ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Percentage__c</fullName>
        <label>Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>ER_Approval_Trigger_Value__c</fullName>
        <label>Approval Trigger Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Pricebook2.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Configuration__c</fullName>
        <label>Configuration</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Displayed</fullName>
                    <default>true</default>
                    <label>Displayed</label>
                </value>
                <value>
                    <fullName>SelectedOptional</fullName>
                    <label>Selected Optional</label>
                </value>
                <value>
                    <fullName>SelectedMandatory</fullName>
                    <label>Selected Mandatory</label>
                </value>
                <value>
                    <fullName>SelectedHidden</fullName>
                    <label>Selected Hidden</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Percentage__c</fullName>
        <label>Percentage</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Line_Order__c</fullName>
        <label>Line Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ER_Minimum_Fee__c</fullName>
        <label>Minimum Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ER_Solution_Code__c</fullName>
        <formula>IF(
BEGINS(ER_Solution__r.ProductCode, &quot;ERHU&quot;),  
IF(OR(BEGINS(ProductCode, &quot;SRV_PART&quot;),CONTAINS(ProductCode, &quot;Bonus&quot;)), &quot;Bonus_Card&quot;, &quot;Gift@Schooling Card Hungary&quot;) ,
ER_Solution__r.ProductCode)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Solution Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Solution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Solution</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Solution</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VFCER05_Opportunity_EditPrice.cls
/*
----------------------------------------------------------------------
-- - Name          : VFCER05_Opportunity_EditPrice
-- - Author        : OLA
-- - Description   : The controller of the page VFER05_Opportunity_EditPrice
--
-- Date         Name                Version     Remarks
-- -----------  -----------         --------    ---------------------------------------
--  Dec-2018       OLA                 1.0         Initial version
---------------------------------------------------------------------------------------
*/

global class VFCER05_Opportunity_EditPrice {

	//public String opportunityId;
	public Opportunity opportunityRecord {get; set;}
	public String priceBookName {get; set;}
	public List<String> opportunityFields;

	public VFCER05_Opportunity_EditPrice(ApexPages.StandardController controller) {

		priceBookName = '';
		//opportunityId = ApexPages.currentPage().getParameters().get('id');

		//opportunityRecord = (Opportunity) controller.getRecord();
		opportunityRecord = new Opportunity();

		if (String.isNotBlank(controller.getId())) {
			opportunityFields = new List<String>();
			opportunityFields.add('Pricebook2.name');
			opportunityFields.add('Pricebook2id');
			opportunityFields.add('AccountId');
			opportunityFields.add('ER_IsAmended__c');
			opportunityFields.add('ER_AmendedFromOpportunity__r.ContractId');
			opportunityFields.add('ER_AmendedFromContract__c');
			opportunityFields.add('ER_BU_Picklist__c');
			
			if (!Test.isRunningTest()) controller.addFields(opportunityFields);

			opportunityRecord = (Opportunity) controller.getRecord();
			//opportunityRecord = [select id, Pricebook2.name, Pricebook2id  from Opportunity where id = : opportunityId];
			if (String.isNotBlank(opportunityRecord.Pricebook2id)) {
				priceBookName = opportunityRecord.Pricebook2.name;
			}
		}
	}

	/**
	* @author Oussama LASFAR
	* @date 19/02/2019 (dd/mm/yyyy)
	* @description getServices : check if the selected solutions are already in an active contract for the linked account
	*/
	public static void checkExistingContract(Map<String,String> solutionMap, String accountId, String contractId) {
		String errorMessage;
		for (Contract contractInst : [Select id, contractNumber, (Select id, ER_solution__c, ER_Product2__r.ER_solution__c, ER_Product2__r.ER_solution__r.Name From ER_contractLineitems__r )
		                              From Contract
		                              Where AccountId = : accountId and Status = 'Activated' and Id !=: contractId]) { //if not amendement contractId is null
			for (ER_ContractLineItem__c cli : contractInst.ER_contractLineitems__r) {
				if (solutionMap.containsKey(cli.ER_solution__c) && String.isNotBlank(cli.ER_Product2__r.ER_solution__c)) {

					//throw new VisualforceException('<span id="' + cli.ER_Product2__r.ER_solution__c + '"><b>' + cli.ER_Product2__r.ER_solution__r.Name + '</b> already in <a href="/' + contractInst.id + '">' + contractInst.contractNumber + '</a></span>');
					errorMessage = Label.LABS_SF_Opp_Price_ProductExistInContract;
					errorMessage = errorMessage.replace('{0}', solutionMap.get(cli.ER_solution__c)).replace('{1}', cli.ER_solution__c).replace('{2}', '/' + contractInst.id).replace('{3}', contractInst.contractNumber);
					
					throw new VisualforceException(errorMessage);
				}
			}
		}
	}

	/**
	* @author Oussama LASFAR
	* @date 27/12/2018 (dd/mm/yyyy)
	* @description getServices : get services linked to the selected solutions in Phase 1
	*/
	@RemoteAction
	global static List<pricebookentry> getServices(List<String> productList, String priceBook2Id, String accountId, Boolean isAmendedOpportunity, String contractId) {

		List<pricebookentry> serviceList;

		if (!productList.isEmpty()) {

			Set<String> productSet = new Set<String>();//Set of selected solutions
			System.debug('productList : ' + productList);
			for (Id productid : productList) {
				productSet.add(productid);
			}

			System.debug('productSet : ' + productSet);
			serviceList = [select id, Name, ER_Configuration__c, UnitPrice, ER_Approval_Trigger_Value__c, product2.Description, product2.ER_solution__c, product2.ER_solution__r.Name, product2.ER_Solution_Code__c, pricebook2.ER_Business_Unit__c, ER_Percentage__c,  isactive, CurrencyIsoCode, product2.ER_Minimum_Fee__c
			               from pricebookentry
			               where product2.ER_solution__c IN : productSet and product2.ER_Type__c = 'service' and pricebook2Id = : priceBook2Id and isactive = true
			                       order by product2.ER_solution__r.ER_Line_Order__c, product2.ER_Line_Order__c asc];

			// Map solution Code and SOlution ID
			Map<String,String> solutionMap = new Map<String,String>();

			for (pricebookentry pbe : serviceList) {
				if(String.isNotBlank(pbe.product2.ER_Solution_Code__c)){

					solutionMap.put(pbe.product2.ER_Solution_Code__c, pbe.product2.ER_solution__c);
				}
			}

			//Check if there is already a contract linked to the solutions selected
			//OLA Update 02042019 check also the CLI Solution Code
			checkExistingContract(solutionMap, accountId, contractId);
		}

		return serviceList;
	}

	/**
	* @author Oussama LASFAR
	* @date 27/12/2018 (dd/mm/yyyy)
	* @description getSolutions : get All Opportunity's pricebook solutions
	*/
	public List<PricebookEntry> getSolutions  {
		get{
			if (opportunityRecord.Id != null) {
				List<PricebookEntry> solutionList = [select id, Name, Pricebook2id, Pricebook2.name, Pricebook2.ER_Business_Unit__c, Product2.id, Product2.ER_Type__c, isactive
				from pricebookentry
				where Product2.ER_Type__c = 'Solution' and Pricebook2id = : opportunityRecord.pricebook2Id and Pricebook2.isactive=true and isactive = true
				order by product2.ER_Line_Order__c, Name asc];
				System.debug('###getSolutions : ' + solutionList);
				return solutionList;
			}

			return new List<PricebookEntry>();
		}
		set {}
	}

    /**
    * @author Oussama LASFAR
    * @date 15/10/2019 (dd/mm/yyyy)
    * @description getProductDependencies : get Products dependencies
    */
    @RemoteAction
    public static Map<Id, ER_Product_Dependency__c> getProductDependencies(String oppBusinessUnit) {
        
        Map<Id, ER_Product_Dependency__c> mapProductDependencies = new Map<Id, ER_Product_Dependency__c>([SELECT id, ER_Controlling_Product__c, ER_Controlling_Product__r.Name, ER_Controlling_Product__r.ER_Solution__c, ER_Dependent_Product__c, ER_Dependent_Product__r.Name, ER_Dependent_Product__r.ER_Solution__c, ER_Configuration__c
                                                 FROM ER_Product_Dependency__c
                                                 WHERE ER_Controlling_Product__r.ER_Business_Unit__c =: oppBusinessUnit AND ER_Dependent_Product__r.ER_Business_Unit__c =: oppBusinessUnit
                                                 AND ER_Controlling_Product__r.IsActive = true AND ER_Dependent_Product__r.IsActive = true]);

        return mapProductDependencies;
    }    

	/**
	* @author Oussama LASFAR
	* @date 27/12/2018 (dd/mm/yyyy)
	* @description saveOpportunityProducts : save selected opportunity line items and update current opportunity fields : ER_NeedApproval__c & ER_Approved__c
	*/
	@RemoteAction
	global static Id saveOpportunityProducts(List<OpportunityLineItem> lineItemsToSave, String opportunityId) {

		Set<Id> setOli = new Set<Id>();
		for (OpportunityLineItem oli : lineItemsToSave) {
			setOli.add(oli.Id);
		}
		System.debug('lineItemsToSave :' + lineItemsToSave);

		delete [select id from OpportunityLineItem where opportunityId = : opportunityId AND id NOT IN : setOli];

		upsert lineItemsToSave;

		Opportunity currentOpportunity = new Opportunity();
		currentOpportunity.id = opportunityId;
		currentOpportunity.ER_NeedApproval__c = false;
		currentOpportunity.ER_Approved__c = false;

		update currentOpportunity;

		return null;
	}

	/**
	* @author Oussama LASFAR
	* @date 27/12/2018 (dd/mm/yyyy)
	* @description getOpportunityProduct : get Products linked to the current Opportunity
	*/
	@RemoteAction
	global static Map<String, OpportunityLineItem> getOpportunityProduct(String opportunityId) {

		Map<String, OpportunityLineItem> mapProductOli = new Map<String, OpportunityLineItem>();
		List<OpportunityLineItem> oliList = [select id, OpportunityId, Product2Id, Product2.ER_Solution__c, ER_Percentage__c, UnitPrice,
		                                     ListPrice, Quantity, ER_Minimum_Fee__c, Discount
		                                     from OpportunityLineItem
		                                     where opportunityid = : opportunityId];

		System.debug('###oliList : ' + oliList);

		for (OpportunityLineItem oli : oliList) {

			mapProductOli.put(oli.Product2Id, oli);
		}

		return mapProductOli;
	}
    
    

	public class VisualforceException extends Exception {}
}