src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Creation_date_in_OS__c</fullName>
        <description>Use as a reference for EDG data creation</description>
        <label>Creation date in OS</label>
        <type>DateTime</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ER_ContractLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>ER_Contract__r.ER_Business_Unit__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>ER_ContractLineItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Creation_date_in_OS__c</fullName>
        <label>Creation date in OS</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ER_ListPrice__c</fullName>
        <label>Standard Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ER_NeedApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Approval ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Percentage__c</fullName>
        <label>Percentage</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>ER_PricebookEntryId__c</fullName>
        <label>Price Book Entry ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Quantity__c</fullName>
        <label>Quantity</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ER_UnitPrice__c</fullName>
        <label>Sales Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Contract Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ER_AmendedFromContract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amended From Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Amended Opportunities</relationshipLabel>
        <relationshipName>AmendedOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_NeedApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Approval ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_PaymentMethod__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BU_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ER_Payment_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_PaymentTerms__c</fullName>
        <label>Payment Terms</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BU_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ER_Payment_Terms</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Upselling</fullName>
                </value>
                <value>
                    <fullName>Cross selling</fullName>
                </value>
                <value>
                    <fullName>Regain</fullName>
                </value>
                <value>
                    <fullName>Digitalisation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_ReimbursementTerm__c</fullName>
        <label>Reimbursement Term</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BU_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ER_Reimbursement_Term</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_InvoicingFrequency__c</fullName>
        <label>Invoicing Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BU_Picklist__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ER_Invoicing_Frequency</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_IsAmended__c</fullName>
        <formula>OR(
            NOT(ISBLANK(ER_AmendedFromOpportunity__c)),
            NOT(ISBLANK(ER_AmendedFromContract__c))
            )
        </formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amended ?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Creation_date_in_OS__c</fullName>
        <label>Creation date in OS</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ER_NeedApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need Approval ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ER_Percentage__c</fullName>
        <label>Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <defaultValue>&apos;--None--&apos;</defaultValue>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/globalValueSets/ER_Invoicing_Frequency.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Per order</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quaterly</fullName>
    </customValue>
    <customValue>
        <fullName>Semi-Yearly</fullName>
    </customValue>
    <customValue>
        <fullName>Yearly</fullName>
    </customValue>
    <masterLabel>Invoicing Frequency</masterLabel>
</GlobalValueSet>

src/globalValueSets/ER_Payment_Method.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Direct debit</fullName>
    </customValue>
    <customValue>
        <fullName>Bank transfer</fullName>
    </customValue>
    <customValue>
        <fullName>Cheque</fullName>
    </customValue>
    <customValue>
        <fullName>Cash</fullName>
    </customValue>
    <masterLabel>Payment Method</masterLabel>
</GlobalValueSet>

src/globalValueSets/ER_Payment_Terms.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>At reception of invoice</fullName>
    </customValue>
    <customValue>
        <fullName>3 days after invoice issuance</fullName>
    </customValue>
    <customValue>
        <fullName>5 days after invoice issuance</fullName>
    </customValue>
    <customValue>
        <fullName>7 days after invoice issuance</fullName>
    </customValue>
    <customValue>
        <fullName>10 days after invoice issuance</fullName>
    </customValue>
    <customValue>
        <fullName>14 days after invoice issuance</fullName>
    </customValue>
    <customValue>
        <fullName>20 days after invoice issuance</fullName>
    </customValue>
    <customValue>
        <fullName>30 days after invoice issuance</fullName>
    </customValue>
    <customValue>
        <fullName>45 days after invoice issuance</fullName>
    </customValue>
    <customValue>
        <fullName>60 days after invoice issuance</fullName>
    </customValue>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

src/globalValueSets/ER_Reimbursement_Term.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>3 days</fullName>
    </customValue>
    <customValue>
        <fullName>4 days</fullName>
    </customValue>
    <customValue>
        <fullName>5 days</fullName>
    </customValue>
    <customValue>
        <fullName>7 days</fullName>
    </customValue>
    <customValue>
        <fullName>10 days</fullName>
    </customValue>
    <customValue>
        <fullName>14 days</fullName>
    </customValue>
    <customValue>
        <fullName>15 days</fullName>
    </customValue>
    <customValue>
        <fullName>30 days</fullName>
    </customValue>
    <customValue>
        <fullName>60 days</fullName>
    </customValue>
    <masterLabel>Reimbursement Term</masterLabel>
</GlobalValueSet>

src/classes/APER04_Opportunity_Management.cls
/*
----------------------------------------------------------------------
-- - Name          : APER04_Opportunity_Management
-- - Author        : OLA
-- - Description   : User Management, This class is used to group all the functionnality linked to the object Opportunity()
--
-- Date         Name                Version     Remarks
-- -----------  -----------         --------    ---------------------------------------
--  JAN-2019       OLA                 1.0         Initial version
---------------------------------------------------------------------------------------
*/
public class APER04_Opportunity_Management {

	public static void updateOpportunityStage(Set<Id> opportunityIds, String stageName) {

		List<Opportunity> opportunityListToUpdate = new List<Opportunity>();
		Opportunity opportunityToUpdate = new Opportunity();

		for (Id opportunityId : opportunityIds) {

			opportunityToUpdate = new Opportunity(Id = opportunityId);
			opportunityToUpdate.StageName = stageName;
			opportunityListToUpdate.add(opportunityToUpdate);
		}
		if (!opportunityListToUpdate.isEmpty()) {

			System.debug('opportunityListToUpdate : ' + opportunityListToUpdate);
			update opportunityListToUpdate;
		}
	}

	public static void updateOpportunityContract(List<Opportunity> opportunityList) {

		update opportunityList;
	}

	@AuraEnabled
	public static List<Opportunity> getOpportunityRecord(String opportunityId) {

		List<Opportunity> opportunityList = [select Id, Name, AccountId, StageName, CloseDate, PriceBook2Id, CurrencyIsoCode, ER_IsAmended__c, ER_InvoicingFrequency__c, ER_PaymentTerms__c, ER_PaymentMethod__c, ER_ReimbursementTerm__c, ER_Reason__c from Opportunity where id = :opportunityId];
		return opportunityList;
	}

	@AuraEnabled
	public static void discardAmendement(String opportunityId) {

		delete [select id from Opportunity where id = :opportunityId];
	}

	/*
	* LASFAR
	* 14/02/2019
	* createOpportunityFromContract : Create new Opportunity from the current contract (contract came from data init)
	*/
	public static Opportunity createOpportunityFromContract(String contractId, String opportunityId) {

		Opportunity newOpp;
		OpportunityLineItem oli;
		List<OpportunityLineItem> oliToInsert = new List<OpportunityLineItem>();
		Boolean userCanAmend = false;

		try {
			for (Contract contractInst : [Select id, AccountId, Account.Name, Pricebook2Id, CurrencyIsoCode, ER_business_unit__c, (Select id, ER_NeedApproval__c, ER_ListPrice__c, ER_UnitPrice__c, CurrencyIsoCode, ER_PricebookEntryId__c, ER_Quantity__c, ER_Percentage__c, ER_Card_Operational_System_ID__c, ER_Creation_date_in_OS__c From ER_ContractLineItems__r)
			From Contract
			Where id = :contractId and ER_business_unit__c =: APER10_User_Management.userBU]) {

				userCanAmend = true;

				if(String.isNotBlank(opportunityId)){
					// CLone Existing Opportunity
					List<Opportunity> linkedOpportunity = APER04_Opportunity_Management.getOpportunityRecord(opportunityId);
					if(!linkedOpportunity.isEmpty()){
						newOpp = linkedOpportunity[0].clone(false, true, false, false);
						newOpp.Name = Datetime.now().format('YYYYMMdd')+' - '+linkedOpportunity[0].Name;
						newOpp.StageName = Label.LABS_SF_Opp_Status_Qualification;
						newOpp.CloseDate = Date.today().addMonths(1);
						newOpp.ER_AmendedFromContract__c = contractInst.id;
					}
				}
				if(newOpp == null){
					//create New Opportunity
					newOpp = new Opportunity();
					newOpp.Name = Datetime.now().format('YYYYMMdd')+' - '+contractInst.Account.Name;
					newOpp.AccountId = contractInst.AccountId;
					newOpp.ER_AmendedFromContract__c = contractInst.id;
					newOpp.Pricebook2Id = contractInst.Pricebook2Id;
					newOpp.StageName = Label.LABS_SF_Opp_Status_Qualification;
					newOpp.CloseDate = Date.today().addMonths(1);
					newOpp.CurrencyIsoCode = contractInst.CurrencyIsoCode;
				}
				

				insert newOpp; // inside loop but one instance maximum !

				for (ER_ContractLineItem__c cli : contractInst.ER_ContractLineItems__r) {

					oli = new OpportunityLineItem();
					oli.OpportunityId = newOpp.id;
					oli.UnitPrice = cli.ER_UnitPrice__c;
					oli.PricebookEntryId = cli.ER_PricebookEntryId__c;
					oli.Quantity = cli.ER_Quantity__c;
					oli.ER_Percentage__c = cli.ER_Percentage__c;
					oli.ER_NeedApproval__c = cli.ER_NeedApproval__c;
					oli.ER_Creation_date_in_OS__c = cli.ER_Creation_date_in_OS__c;
					oli.ER_Card_Operational_System_ID__c = cli.ER_Card_Operational_System_ID__c;
					oliToInsert.add(oli);
				}
			}

			if (!oliToInsert.isEmpty()) {

				System.debug('oliToInsert : ' + oliToInsert);
				insert oliToInsert;
			}
			else if(!userCanAmend){

				System.debug('User cannot Amend ! ');
				throw new APER04_Opportunity_Exception(Label.LABS_SF_AvoidAmendement);
			}
		} catch (Exception e) {

			throw new AuraHandledException(e.getMessage());
		}

		return newOpp;
	}

	public class APER04_Opportunity_Exception extends Exception {}
}