src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Company_Type__c</fullName>
        <label>Company Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Institution</fullName>
                </value>
                <value>
                    <fullName>Private (work for Institution)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Legal_Form__c</fullName>
        <label>Legal Form</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Legal_Form</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/IT_Usage__c.object
<CustomObject>
    <label>Usage</label>
    <nameField>
        <displayFormat>2020-{0000}</displayFormat>
        <label>Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>IT_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date of Use</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IT_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IT_Used_Quantity__c</fullName>
        <label>Used Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/default/objects/IT_Usage__c/fields/Subscription_Product_Charge__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Product_Charge__c</fullName>
    <label>Subscription Product &amp; Charge</label>
    <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
    <relationshipLabel>Usage</relationshipLabel>
    <relationshipName>Usage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Zuora__CustomerAccount__c.object
<CustomObject>
</CustomObject>

src/objects/Zuora__Subscription__c.object
<CustomObject>
</CustomObject>

src/objects/Zuora__SubscriptionProductCharge__c.object
<CustomObject>
</CustomObject>

force-app/main/default/classes/APIT00_PostUsage_Test.cls
@isTest private class APIT00_PostUsage_Test {
   static testMethod void createRecord() { 
      RecordType personAccountRecordType =  [SELECT Id FROM RecordType where SobjectType='Account' and Developername='PersonAccount' Limit 1];
        
        Account result = new Account(
            IT_Company_Type__c = 'Institution',
            IT_Legal_Form__c = 'SPA',
            FirstName = 'TestName',
            LastName = 'TestSurname',
            PersonEmail =  'personalEmail@gmail.com',
            Phone = '12345679',
            PersonMobilePhone = '16844838',
            RecordTypeId = personAccountRecordType.Id,
            ER_VAT_Number__c ='03183450232'
        );
       insert result;
       
       Zuora__CustomerAccount__c cuAccTest = new Zuora__CustomerAccount__c(Zuora__AccountNumber__c='100000',
                                                                          Zuora__Account__c=result.id,
                                                                          Name='Bill1',
                                                                          Zuora__Zuora_Id__c='123456789testttttt');
       insert cuAccTest;
       Zuora__Subscription__c subTest= new Zuora__Subscription__c(Name = 'TestSub',
                                                                 Zuora__CustomerAccount__c=cuAccTest.id);
                                                                  //,Zuora__SubscriptionNumber__c='A-S00000000');
       insert subTest;
       Zuora__UnitOfMeasure__c uomTest = new Zuora__UnitOfMeasure__c(Name='<abc>Day');
       insert uomTest;
       Zuora__SubscriptionProductCharge__c subProChaTest = new Zuora__SubscriptionProductCharge__c(Zuora__Subscription__c=subTest.id,
                                                                                                  Zuora__ChargeNumber__c='C-00000000',
                                                                                                  Zuora__UOM__c='Day',
                                                                                                  Zuora__UnitOfMeasure__c=uomTest.id);
       insert subProChaTest;
       IT_Usage__c usageTest = new IT_Usage__c (Subscription_Product_Charge__c=subProChaTest.Id,
                                                IT_Used_Quantity__c=1,
                                                IT_Date__c= System.today(),
                                                IT_Description__c='TestApex');
       insert usageTest;
       
       List<IT_Usage__c> itUsa= new List<IT_Usage__c>();
       itUsa.add(usageTest);
       
       APIT00_PostUsage.newUsage(itUsa);
       
       String ZuoraID ='123456789abcdef';
       String id_usa=usageTest.id;
       APIT00_PostUsage.saveID(ZuoraID,id_usa);
       
       delete usageTest;
   }
  
}