src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IT_Change_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Change_VAT_Group__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change VAT Group</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/ER_Delivery_Site__c.object
<CustomObject>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Delivery Sites</relationshipLabel>
        <relationshipName>Delivery_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Change_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change Address</label>
        <type>Checkbox</type>
    </fields>
    <label>Delivery Site</label>
    <nameField>
        <label>Delivery Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Distribution_Point__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/ER_Distribution_Point__c/fields/ER_Delivery_Site__c.field-meta.xml
<CustomField>
    <fullName>ER_Delivery_Site__c</fullName>
    <label>Delivery Site</label>
    <referenceTo>ER_Delivery_Site__c</referenceTo>
    <relationshipLabel>Distribution Points</relationshipLabel>
    <relationshipName>Distribution_Points</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>IT_Change_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change Address</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/APIT17_QueueableCallGenericService.cls
public with sharing class APIT17_QueueableCallGenericService implements Queueable {
    String stringJson;
    
    public APIT17_QueueableCallGenericService(String jsonCall, List<SObject> updateFlags, String nameObject){
        List<SObject> updateFlagsTotal = new List<SObject>();
        System.debug('updateFlags: '+updateFlags);
        System.debug('nameObject: '+nameObject);
        if(nameObject == 'Account' || nameObject == 'ER_Financial_Center__c' || nameObject == 'ER_Delivery_Site__c' || nameObject == 'ER_Distribution_Point__c'){
            for(SObject singleObj : updateFlags){
                Object updateFlagsSingle;
                Map<String,Object> mapObj = (Map<String,Object>)Json.deserializeUntyped(Json.serialize(singleObj));
                Boolean TriggerControl = false;
                if(mapObj != null && mapObj.Keyset().contains('IT_Change_Address__c') && mapObj.get('IT_Change_Address__c') == true){
                    System.debug('mapObj.getAddress: '+mapObj.get('IT_Change_Address__c'));
                    mapObj.put('IT_Change_Address__c', false);
                    TriggerControl = true;  
                }
                if(TriggerControl){
                    String cObjJsonDrunk = JSON.serialize(mapObj);
                    SObject customObject = (SObject)JSON.deserialize(cObjJsonDrunk, Sobject.class);
                    System.debug('customObject: '+customObject);
                    if(null != mapObj.get('IT_Change_VAT_Group__c') && nameObject == 'Account'){
                        updateFlagsTotal.add(customObject); 
                        System.debug('mapObj: '+mapObj);
                        System.debug('updateFlagsTotal: '+updateFlagsTotal); 
                    }
                    if(nameObject != 'Account'){
                        updateFlagsTotal.add(customObject); 
                        System.debug('mapObj: '+mapObj);
                        System.debug('updateFlagsTotal: '+updateFlagsTotal); 
                    }
                }      

                System.debug('mapObj.getPost: '+mapObj.get('IT_Change_VAT_Group__c'));   
            }
            if(updateFlagsTotal != null && updateFlagsTotal.size() > 0)
                update updateFlagsTotal;
        }    

        this.stringJson = jsonCall;
    }
      
    public void execute(QueueableContext context){
        System.debug('context: '+context);
        //APIT11_Utilities.postRequest('clients', stringJson);
    }   
}