src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is the unique identifier of the customer on Middle Office side. It is used to link a Salesforce record with a Middle Office record</inlineHelpText>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IT_Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Bank_Account__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/ER_Bank_Account__c/fields/ER_Financial_Center__c.field-meta.xml
<CustomField>
    <fullName>ER_Financial_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Center</label>
    <referenceTo>ER_Financial_Center__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ER_Bank_Account__c/fields/IT_Client_Code__c.field-meta.xml
<CustomField>
    <fullName>IT_Client_Code__c</fullName>
    <label>Client Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

src/objects/ER_ContractLineItem__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Client_Code__c</fullName>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Contract Line Items</relationshipLabel>
        <relationshipName>Contract_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Line Item</label>
    <nameField>
        <label>Contract Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ER_Delivery_Site__c.object
<CustomObject>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Delivery Sites</relationshipLabel>
        <relationshipName>Delivery_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Client_Code__c</fullName>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Delivery_AC__c</fullName>
        <label>Delivery AC</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Delivery Site</label>
    <nameField>
        <label>Delivery Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Distribution_Point__c.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/ER_Distribution_Point__c/fields/ER_Delivery_Site__c.field-meta.xml
<CustomField>
    <fullName>ER_Delivery_Site__c</fullName>
    <label>Delivery Site</label>
    <referenceTo>ER_Delivery_Site__c</referenceTo>
    <relationshipLabel>Distribution Points</relationshipLabel>
    <relationshipName>Distribution_Points</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_AC_Activity__c.field-meta.xml
<CustomField>
    <fullName>IT_AC_Activity__c</fullName>
    <label>AC Activity</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Client_Code__c.field-meta.xml
<CustomField>
    <fullName>IT_Client_Code__c</fullName>
    <label>Financial Center</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Financial_Center__c.field-meta.xml
<CustomField>
    <fullName>IT_Financial_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Center</label>
    <referenceTo>ER_Financial_Center__c</referenceTo>
    <relationshipLabel>Distribution Points</relationshipLabel>
    <relationshipName>Distribution_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Bank_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Account</label>
        <referenceTo>ER_Bank_Account__c</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers_BankAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Card_Operational_System_ID__c</fullName>
        <externalId>true</externalId>
        <label>Card Operational System ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Merchant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>IT_Client_Code__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Contact_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Detail</label>
        <referenceTo>IT_Contact_Detail__c</referenceTo>
        <relationshipLabel>Contact Detail</relationshipLabel>
        <relationshipName>Contact_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Delivery_AC__c</fullName>
        <label>Delivery AC</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Contact Detail</relationshipLabel>
        <relationshipName>Contact_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Association</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Contact Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Association</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_Contact_Detail__c.object
<CustomObject>
    <fields>
        <fullName>IT_Code__c</fullName>
        <label>Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Contact Details</relationshipLabel>
        <relationshipName>Contact_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Detail</label>
    <nameField>
        <label>Contact Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_Group__c.object
<CustomObject>
    <fields>
        <fullName>IT_Group_Code__c</fullName>
        <externalId>true</externalId>
        <label>Group Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_Group_Code__c.object
<CustomObject>
    <fields>
        <fullName>ER_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Code</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Groups Code</relationshipLabel>
        <relationshipName>Groups_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Client_Code__c</fullName>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Group_Code__c</fullName>
        <label>Group Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Group Code</label>
    <nameField>
        <label>Group Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_Request__c.object
<CustomObject>
    <fields>
        <fullName>IT_Client_Code__c</fullName>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/APIT12_CallOutbound_Test.cls
@isTest
public class APIT12_CallOutbound_Test {
    @isTest
    static void CallOutbound(){
        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        accountTest.ER_VAT_Number__c = '02554698475';
        insert accountTest;
        Contact contactTest = APIT14_DataFactory.create_Contact(accountTest.Id);
        contactTest.IT_Code__c = 'StringString';
        insert contactTest;
        IT_Contact_Detail__c contactDetailTest = APIT14_DataFactory.create_Contact_Detail(contactTest.Id);
        contactDetailTest.IT_Code__c = 'StringString';
        insert contactDetailTest;
        ER_Financial_Center__c FinancialTest = APIT14_DataFactory.create_FinancialCenter(accountTest.Id, contactTest.Id);
        FinancialTest.ER_Card_Operational_System_ID__c = 'Tes2w';
        FinancialTest.ER_Type__c = 'Client'; 
        FinancialTest.IT_Financial_Center__c = '445566';
        insert FinancialTest;
        ER_Delivery_Site__c deliverysiteTest = APIT14_DataFactory.create_DeliverySite(FinancialTest.Id, accountTest.Id);
        deliverysiteTest.IT_Delivery_AC__c = '555666';
        insert deliverysiteTest;
        ER_Distribution_Point__c distributionPointTest = APIT14_DataFactory.create_DistributionPoint(FinancialTest.Id, deliverysiteTest.Id);
        distributionPointTest.IT_AC_Activity__c = 'lkjhg';
        insert distributionPointTest;
        ER_Bank_Account__c bankAccountTest = APIT14_DataFactory.create_BankAccount(FinancialTest.Id);
        bankAccountTest.IT_Client_Code__c = '445566';
        insert bankAccountTest;

        IT_Group_Code__c groupCodeTest = APIT14_DataFactory.create_GroupCode(FinancialTest.Id);
        groupCodeTest.IT_Client_Code__c = '445566';
        insert groupCodeTest;
        Contract contractTest = APIT14_DataFactory.create_Contract(accountTest.Id);
        insert contractTest;
        ER_ContractLineItem__c contractLineItemTest = APIT14_DataFactory.create_ContractLineItem(contractTest.Id);
        insert contractLineItemTest;
        IT_Contact_Association__c contactASSTest = APIT14_DataFactory.create_ContactASS(contactDetailTest.Id, FinancialTest.Id);
        insert contactASSTest;
        IT_Intent_Declaration__c intentDeclarationTest = APIT14_DataFactory.create_IntentDeclaration(accountTest.Id);
        insert intentDeclarationTest;
        IT_Group__c groupTest = APIT14_DataFactory.create_Group(FinancialTest.Id);
        insert groupTest;
        
        update contactTest;
        update contactDetailTest;
        FinancialTest.IT_Send_SUT_Printout__c = true;
        update FinancialTest;
        FinancialTest.IT_Opening_Outcome__c = '001';
        update FinancialTest;
        FinancialTest.IT_Change_Address__c = true;
        update FinancialTest;
        update deliverysiteTest;
        deliverysiteTest.IT_Change_Address__c = true;
        update deliverysiteTest;
        update distributionPointTest;
        distributionPointTest.IT_Change_Address__c = true;
        update distributionPointTest;
        update bankAccountTest;
        update groupCodeTest;
        update contractLineItemTest;
        update contactASSTest;
        update contractTest;
        contractTest.IT_Change_Document__c = true;
        update contractTest;
        contractTest.IT_Change_Economic_Conditions__c = true;
        update contractTest;
        update intentDeclarationTest;
        update groupTest;

        IT_Request__c reqTest = APIT14_DataFactory.create_Request(FinancialTest.Id);
        reqTest.IT_Client_Code__c = '445566';
        insert reqTest;

    }
    
    @isTest
    static void CallOutboundAccount(){
        Account accountTest = APIT14_DataFactory.create_BusinessAccount();
        accountTest.ER_VAT_Number__c = '02554698475';
        insert accountTest;
        update accountTest;

    }  
}