src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(CreatedBy.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>ER_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>ER_Employee__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ER_Individual_Account_RT</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>ER_BUPicklist__c</fullName>
        <defaultValue>$User.ER_BUText__c</defaultValue>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <formula>TEXT(Owner:User.ER_Business_Unit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Card_Number__c</fullName>
        <label>Card Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_CaseReason2__c</fullName>
        <label>Case Detailed Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_Reason__c</controllingField>
            <valueSetDefinition>
                <value>
                <fullName>Asset not received</fullName>
                </value>
                <value>
                    <fullName>Balance enquiry</fullName>
                </value>
                <value>
                    <fullName>Transaction enquiry</fullName>
                </value>
                <value>
                    <fullName>Mobile App</fullName>
                </value>
                <value>
                    <fullName>Payment Topics</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Bank account modification</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy</fullName>
                </value>
                <value>
                    <fullName>Financial Topic</fullName>
                </value>
                <value>
                    <fullName>Copy of contract</fullName>
                </value>
                <value>
                    <fullName>Company change</fullName>
                </value>
                <value>
                    <fullName>Card acceptance issue</fullName>
                </value>
                <value>
                    <fullName>Store locator</fullName>
                </value>
                <value>
                    <fullName>Collection</fullName>
                </value>
                <value>
                    <fullName>Relationship</fullName>
                </value>
                <value>
                    <fullName>Special requests (reports, GDPR)</fullName>
                </value>
                <value>
                    <fullName>Acceptance Network</fullName>
                </value>
                <value>
                    <fullName>Card activation</fullName>
                </value>
                <value>
                    <fullName>Permanently block card</fullName>
                </value>
                <value>
                    <fullName>Unblock card</fullName>
                </value>
                <value>
                    <fullName>Apple Pay</fullName>
                </value>
                <value>
                    <fullName>Google Pay</fullName>
                </value>
                <value>
                    <fullName>Acceptance</fullName>
                </value>
                <value>
                    <fullName>Validity</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Unblock</fullName>
                </value>
                <value>
                    <fullName>Characteristic</fullName>
                </value>
                <value>
                    <fullName>Card</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>ER_Employee__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Individual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_Reason__c</fullName>
        <label>Case Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ER_BUPicklist__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ER_Card</fullName>
                    <label>Card</label>
                </value>
                <value>
                    <fullName>ER_Voucher</fullName>
                    <label>Voucher</label>
                </value>
                <value>
                    <fullName>ER_Mobile_App</fullName>
                    <label>Mobile App</label>
                </value>
                <value>
                    <fullName>ER_Reimbursement</fullName>
                    <label>Reimbursement</label>
                </value>
                <value>
                    <fullName>ER_Payment</fullName>
                    <label>Payment</label>
                </value>
                <value>
                    <fullName>ER_General_Information</fullName>
                    <label>General Information</label>
                </value>
                <value>
                    <fullName>ER_Order_Delivery</fullName>
                    <label>Order &amp; Delivery</label>
                </value>
                <value>
                    <fullName>ER_Extranet</fullName>
                    <label>Extranet</label>
                </value>
                <value>
                    <fullName>ER_Contract_modification</fullName>
                    <label>Contract &amp; modification</label>
                </value>
                <value>
                    <fullName>ER_Company_changes</fullName>
                    <label>Company changes</label>
                </value>
                <value>
                    <fullName>ER_Card_acceptance</fullName>
                    <label>Card acceptance</label>
                </value>
                <value>
                    <fullName>ER_Invoicing</fullName>
                    <label>Invoicing</label>
                </value>
                <value>
                    <fullName>ER_Validity</fullName>
                    <label>Validity</label>
                </value>
                <value>
                    <fullName>ER_Complaint</fullName>
                    <label>Complaint</label>
                </value>
                <value>
                    <fullName>ER_Online_support</fullName>
                    <label>Online support</label>
                </value>
                <value>
                    <fullName>ER_Others</fullName>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>ER_Finance</fullName>
                    <label>Finance</label>
                </value>
            <value>
                    <fullName>Acceptance network</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>ER_User_Case_RT</fullName>
        <active>true</active>
        <businessProcess>User Support</businessProcess>
        <description>Record Type for the User Case</description>
        <label>ER User Case RT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Employee__c.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Individual</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ER_Business_Unit__c</fullName>
        <defaultValue>&apos;--None--&apos;</defaultValue>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/APER08_Case_Management.cls
/*
----------------------------------------------------------------------
-- - Name          : APER08_Case_Management
-- - Author        : OLA
-- - Description   : Case Management, This class is used to group all the functionnality linked to the object Case
--
-- Date         Name                Version     Remarks
-- -----------  -----------         --------    ---------------------------------------
--  Nov-2018       OLA                 1.0         Initial version
---------------------------------------------------------------------------------------
*/
public class APER08_Case_Management {
    
    public static void completeMilestone( Map<String,List<Id>> CaseMilestone, DateTime complDate) { 
        List<Id> caseIds = new List<Id>();
        for(List<Id> ids : CaseMilestone.values()){
            caseIds.addall(ids);
        }
        
        List<CaseMilestone> cmsToUpdate = [select Id, completionDate
                                           from CaseMilestone cm
                                           where caseId in : caseIds and cm.MilestoneType.Name IN :CaseMilestone.keyset() 
                                           and completionDate = null];
        
        if (!cmsToUpdate.isEmpty()){
            for (CaseMilestone cm : cmsToUpdate){ cm.completionDate = complDate; }
            
            update cmsToUpdate;
        }
    }
    
    /*
    *
    * OLA
    * Nov 2018
    * GetEmployeeCaseOptions: This method is used to get all the cases per Employee:
    *                         The purpose is to give the posibility to the User to link an activity to an existing Case
    *
    */

    Public Static List<SelectOption> GetEmployeeCaseOptions(String Employee){ 
        System.debug('GetEmployeeCaseOptions Employee : '+Employee);
        List<SelectOption> caseOptions = new List<SelectOption>();
        caseOptions.add(new SelectOption('','--'+Label.LAB_SF_None+'--'));
        
        if(String.isNotBlank(Employee)){
            List<Case> cases = GetEmployeeCases(Employee);
            System.debug('GetEmployeeCaseOptions cases : '+cases);
            if(!cases.isEmpty()){
                for(Case c:cases){
                    caseOptions.add(new SelectOption(c.Id+'',c.CaseNumber+ (String.isBlank(c.ER_Reason__c)? '' : ' - '+c.ER_Reason__c) )); 
                }
            }
        }
        
        return caseOptions;
    }
    
    /*
    *
    * OLA
    * Nov 2018
    * GetEmployeeCases: This method is used to get all the cases per Employee: 
    *                   The purpose is to give the posibility to the User to link an activity to an existing Case
    *
    */

    Public Static List<Case> GetEmployeeCases(String Employee){  
        System.debug('GetEmployeeCases Employee : '+Employee);
        if(Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ER_User_Case_RT') != null){
            
            String RecordtypeId= Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ER_User_Case_RT').getRecordTypeId();
            string query ='SELECT Id,CaseNumber,toLabel(ER_Reason__c) '
                + ' FROM Case'
                + ' WHERE ER_Employee__c = \'' + Employee +'\''
                + ' AND isclosed= false and recordtypeid = \''+RecordtypeId+'\' order by CaseNumber desc';
            
            return (List<Case>)Database.query(query);
        }
        
        return new List<Case>();
    }
    
    /*
    *
    * OLA
    * Nov 2018
    * CreateCase : Quick case creation with case Reason and Case Detailed Reason
    *              Used to create case after an Asset Action: Block Card/Get Pin Reset
    *
    */
    

    Public Static Case CreateCase(String reason, String detailedReason, String assetID){
        
        Case newCase = new Case();
        newCase.AssetId = assetID;
        newCase.RecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('ER_User_Case_RT').getRecordTypeId();
        newCase.ER_Reason__c = reason;
        newCase.ER_CaseReason2__c = detailedReason;
        insert newCase;
        
        return newCase;
    }

    /*
    *
    * OLA
    * JUN 2019
    * manageCasesFromWeb: This method is used to Linked inserted cases to Asset, Indivudual, Employee and entitlment
    *
    *
    */
    public static void manageCasesFromWeb(List<Case> caseList) {

        Map<String, Asset> assetMap = new Map<String, Asset>();
        Set<String> assetNumberSet = new Set<String>();

        for (Case caseInst : caseList) {
            if (caseInst.ER_Card_Number__c != null) {

                assetNumberSet.add(String.valueOf(caseInst.ER_Card_Number__c));
            }
        }
        for (Asset asset : [Select Name, SerialNumber, ER_Employee__c, ER_Individual__c from Asset where Name IN : assetNumberSet]) {

            assetMap.put(asset.Name, asset);
        }

        if (!assetMap.isEmpty()) {

            for (Case caseInst : caseList) {
                if (caseInst.ER_Card_Number__c != null && assetMap.containsKey(String.valueOf(caseInst.ER_Card_Number__c))) {

                    caseInst.ER_Employee__c  = assetMap.get(String.valueOf(caseInst.ER_Card_Number__c)).ER_Employee__c;
                    caseInst.ER_Individual__c  = assetMap.get(String.valueOf(caseInst.ER_Card_Number__c)).ER_Individual__c;
                    caseInst.AssetId  = assetMap.get(String.valueOf(caseInst.ER_Card_Number__c)).Id;
                }
            }
        }
    }

    /*
    *
    * OLA
    * JUN 2019
    * manageCasesEntitlment: This method is used to Link Entitlemnt to inserted cases
    *
    *
    */
    public static void manageCasesEntitlment(List<Case> caseList) {

        List<Entitlement> entls = [Select Id, StartDate, EndDate, AccountId, AssetId, ER_Business_Unit__c From Entitlement];
        Entitlement defaultEntitlemnt;
        for(Entitlement ent : entls){ // get the Core entitlement First
            if (String.isBlank(ent.ER_Business_Unit__c)) {
                defaultEntitlemnt = ent;
                break;
            }
        }
        for (Case c : caseList) {
            if(defaultEntitlemnt != null){
                c.EntitlementId = defaultEntitlemnt.id;//Core entitlement has no business Unit
            }
            
            for(Entitlement ent : entls){
                if (c.ER_BUPicklist__c == ent.ER_Business_Unit__c) {// Check if there is any specific entitlement.
                    
                    c.EntitlementId = ent.Id;
                }
            }
        }
    }
}