src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Statement__c</fullName>
        <label>Statement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consip BPE 1</fullName>
                </value>
                <value>
                    <fullName>Consip BP 8</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>IT_Client_Consip_Case_RT</fullName>
        <active>true</active>
        <businessProcess>Client Support</businessProcess>
        <label>IT Client Consip Case RT</label>
    </recordTypes>
    <recordTypes>
        <fullName>IT_Client_Support_Case_RT</fullName>
        <active>true</active>
        <businessProcess>Support Process</businessProcess>
        <label>IT Client Support Case RT</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CMIT12_Consip_Milestone_Duration__mdt.object
<CustomObject>
    <fields>
        <fullName>IT_BPE_1_Elettronico__c</fullName>
        <label>BPE 1 Elettronico</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IT_BP_8_Cartaceo__c</fullName>
        <label>BP 8 Cartaceo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IT_BP_8_Elettronico__c</fullName>
        <label>BP 8 Elettronico</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IT_Milestone_Name__c</fullName>
        <label>Milestone Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Consip Milestone Duration</label>
    <pluralLabel>Consip Milestone Durations</pluralLabel>
</CustomObject>

src/objects/Entitlement.object
<CustomObject>
    <fields>
        <fullName>IT_Closing_Milestone_Minute__c</fullName>
        <label>Closing Milestone Minute</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Entitlements</relationshipLabel>
        <relationshipName>Entitlements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Milestone_Take_Over__c</fullName>
        <label>Milestone Take Over</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/APIT06_MilestoneTimeCalculator.cls
global class APIT06_MilestoneTimeCalculator implements Support.MilestoneTriggerTimeCalculator {   
    global Integer calculateMilestoneTriggerTime(String caseId, String milestoneTypeId){
        list<Case> singleCase = [SELECT Priority, EntitlementId, RecordType.DeveloperName, IT_Statement__c, IT_Financial_Center__r.IT_Product2__r.IT_Card__c FROM Case WHERE Id=:caseId];
        list<MilestoneType> mt = [SELECT Name FROM MilestoneType WHERE Id=:milestoneTypeId];
        list<Entitlement> Ent = [SELECT IT_Milestone_Take_Over__c, IT_Closing_Milestone_Minute__c From Entitlement WHERE Id=:singleCase[0].EntitlementId];
        System.debug('MILESTONE NAME:: ' +mt[0].name);
        if(singleCase[0].EntitlementId != null){
            if(singleCase[0].RecordType.DeveloperName == 'IT_Client_Consip_Case_RT' || singleCase[0].RecordType.DeveloperName == 'IT_Client_Support_Case_RT'){ // || singleCase[0].RecordType.DeveloperName == 'IT_Client_Support_Case_RT'
                List<CMIT12_Consip_Milestone_Duration__mdt> msDurationConsip = [SELECT MasterLabel, IT_Milestone_Name__c, IT_BP_8_Cartaceo__c, IT_BP_8_Elettronico__c, IT_BPE_1_Elettronico__c FROM CMIT12_Consip_Milestone_Duration__mdt];
                for(CMIT12_Consip_Milestone_Duration__mdt item : msDurationConsip){
                    if(mt[0].Name == item.IT_Milestone_Name__c){
                        if(singleCase[0].IT_Statement__c == 'Consip BPE 1'){
                            return (integer)item.IT_BPE_1_Elettronico__c;
                        }
                        else if(singleCase[0].IT_Statement__c == 'Consip BP 8'){
                            if(singleCase[0].IT_Financial_Center__r.IT_Product2__r.IT_Card__c){
                                return (integer)item.IT_BP_8_Elettronico__c;
                            }
                            else{
                                return (integer)item.IT_BP_8_Cartaceo__c;
                            }
                        }
                    }
                }
            }
            if(mt[0].Name == 'Take Over'){
                if(Ent[0].IT_Milestone_Take_Over__c != null){
                    return (integer)Ent[0].IT_Milestone_Take_Over__c;
                }
                else{
                    return 100;
                }
            }
            else if(Ent[0].IT_Closing_Milestone_Minute__c != null){
                return (integer)Ent[0].IT_Closing_Milestone_Minute__c;
            }
            else{
                return 100;
            }
        }
        else{
            return 100;
        }
        
        
    }
}