src/objects/CMIT07_Legacy_Systems__mdt.object
<CustomObject>
    <fields>
        <fullName>IT_Apex__c</fullName>
        <label>Apex</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_CTI__c</fullName>
        <label>CTI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_GestCred__c</fullName>
        <label>GestCred</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_JIRACreate__c</fullName>
        <label>JIRACreate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_JIRAIssue__c</fullName>
        <label>JIRAIssue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Kiwi__c</fullName>
        <label>Kiwi</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_MYDHL__c</fullName>
        <label>MYDHL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_MYTNT__c</fullName>
        <label>MYTNT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Operations__c</fullName>
        <label>Operations</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_PortaleBeneficiari__c</fullName>
        <label>PortaleBeneficiari</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_PortaleIntesa__c</fullName>
        <label>PortaleIntesa</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_PortaliClienti__c</fullName>
        <label>PortaliClienti</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_SgopSgoc__c</fullName>
        <label>SgopSgoc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_SsoBridge__c</fullName>
        <label>SsoBridge</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Legacy System</label>
    <pluralLabel>Legacy Systems</pluralLabel>
</CustomObject>

src/classes/APIT21_IFrameOpenerController.cls
public class APIT21_IFrameOpenerController {
    @AuraEnabled
    public static CMIT07_Legacy_Systems__mdt callLegacyLink() {
        CMIT07_Legacy_Systems__mdt environmentMD = new CMIT07_Legacy_Systems__mdt();
        Boolean orgType = [Select isSandbox From Organization limit 1].isSandbox;
        List<CMIT07_Legacy_Systems__mdt> listMetadata = new List<CMIT07_Legacy_Systems__mdt>();
        listMetadata = [Select MasterLabel, IT_CTI__c, IT_SsoBridge__c, IT_Apex__c, IT_GestCred__c, IT_JIRACreate__c, IT_JIRAIssue__c, IT_Kiwi__c, IT_MYDHL__c, IT_MYTNT__c, IT_Operations__c, IT_PortaleBeneficiari__c, IT_PortaleIntesa__c, IT_PortaliClienti__c, IT_SgopSgoc__c From CMIT07_Legacy_Systems__mdt];
        System.debug('orgType:::: '+orgType);
        if(orgType){
            if(listMetadata != null && listMetadata.size() > 0){
                for(CMIT07_Legacy_Systems__mdt item : listMetadata){
                    if(item.MasterLabel == 'Sandbox')
                        environmentMD = item;
                }
            }    
        }else{
            if(listMetadata != null && listMetadata.size() > 0){
                for(CMIT07_Legacy_Systems__mdt item : listMetadata){
                    if(item.MasterLabel == 'Production')
                        environmentMD = item;
                }
            }
        }
        return environmentMD;   
    }    
    
}