src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ER_FinancialCenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>ER_Financial_Center__c.ER_Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Client_Billing_Recepits__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client Billing Recepits</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Contact_Type__c</fullName>
        <formula>CASE(IT_Type__c,
&quot;Ref&quot;,&quot;[REF]&quot;,
&quot;Soc&quot;,&quot;[SOC]&quot;,
&quot;&quot;)

&amp; &quot; &quot; &amp;

CASE( IT_Type__c , 
&quot;Ref&quot;, FirstName + &quot; &quot; + LastName, 
&quot;Soc&quot;, FirstName + &quot; &quot; + LastName,
&quot;&quot;)</formula>
        <label>Contact Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Ticket_Receipts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ticket Receipts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Type__c</fullName>
        <defaultValue>&quot;Ref&quot;</defaultValue>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cli</fullName>
                </value>
                <value>
                    <fullName>Attv</fullName>
                </value>
                <value>
                    <fullName>Vons</fullName>
                </value>
                <value>
                    <fullName>Ref</fullName>
                    <default>true</default>
                    <label>Ref</label>
                </value>
                <value>
                    <fullName>Soc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_Contact_Association__c.object
<CustomObject>
    <fields>
        <fullName>IT_Billing_Confirm_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Confirm Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Contact_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Detail</label>
        <referenceTo>IT_Contact_Detail__c</referenceTo>
        <relationshipLabel>Contact Detail</relationshipLabel>
        <relationshipName>Contact_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Contact_Info__c</fullName>
        <label>Contact Info</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IT_Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Dettagli Contatto</relationshipLabel>
        <relationshipName>IT_Contact_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Delivery_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Site</label>
        <referenceTo>ER_Delivery_Site__c</referenceTo>
        <relationshipLabel>Contact Detail</relationshipLabel>
        <relationshipName>Contact_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Distribution_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Point</label>
        <referenceTo>ER_Distribution_Point__c</referenceTo>
        <relationshipLabel>Contact Detail</relationshipLabel>
        <relationshipName>Contact_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Contact Detail</relationshipLabel>
        <relationshipName>Contact_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Notifications__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Order_Confirm_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Confirm Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Send_SUT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send SUT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Type__c</fullName>
        <label>Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Contact Association</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Contact Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Association</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_Contact_Detail__c.object
<CustomObject>
    <fields>
        <fullName>IT_Billing_Confirm_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Confirm Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Contact_Info__c</fullName>
        <label>Contact Info</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Details</relationshipLabel>
        <relationshipName>Contact_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Delivery_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delivery Site</label>
        <referenceTo>ER_Delivery_Site__c</referenceTo>
        <relationshipLabel>Contact Details</relationshipLabel>
        <relationshipName>Contact_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Distribution_Point__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Point</label>
        <referenceTo>ER_Distribution_Point__c</referenceTo>
        <relationshipLabel>Contact Details</relationshipLabel>
        <relationshipName>Contact_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Center</label>
        <referenceTo>ER_Financial_Center__c</referenceTo>
        <relationshipLabel>Contact Details</relationshipLabel>
        <relationshipName>Contact_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Notifications__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notifications</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Order_Confirm_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Order Confirm Address</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Detail</label>
    <nameField>
        <label>Contact Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APIT23_DetailListController.cls
public class APIT23_DetailListController {
    
    //private static String query = 'SELECT Id, Name, FirstName, LastName, Email, MobilePhone FROM Contact';
    @AuraEnabled
    public static ResultWrapper getData( Integer pageSize, Integer pageNumber, String sortBy, String sortOrder, String recordId, boolean isViewAll, boolean isAssociation ){
        List<ER_Financial_Center__c> fincentList = [SELECT id, ER_Account_Name__c FROM ER_Financial_Center__c WHERE id = :recordId];
        String query = 'SELECT id,Name,IT_Contact__c,IT_Contact__r.Name,IT_Contact__r.IT_Client_Billing_Recepits__c,IT_Contact__r.IT_Contact_Type__c,IT_Send_SUT__c,IT_Contact_Detail__c,IT_Contact_Detail__r.Name,IT_Contact_Detail__r.IT_Contact_Info__c,IT_Order_Confirm_Address__c,IT_Financial_Center__c,IT_Financial_Center__r.Name,IT_Billing_Confirm_Address__c,IT_Notifications__c FROM IT_Contact_Association__c WHERE IT_Financial_Center__r.ER_Account_Name__c = \''+fincentList[0].ER_Account_Name__c+'\' AND (IT_Type__c = \'AM\' OR  IT_Type__c = \'Ref\') AND IT_Delivery_Site__c = null AND IT_Distribution_Point__c = null  AND IT_Contact__r.IT_Type__c = \'Soc\' ';
        
        if( sortby != NULL && sortOrder != NULL  ){
            query += ' ORDER BY '+ sortby+' '+ sortOrder+'  NULLS LAST';
        }
        if(!isViewAll){
           query +=  ' LIMIT 10';
        }
       
         
        
            List<IT_Contact_Association__c> contactList = database.query( query );
            if(contactList != null && contactList.size() > 0){
                List<string> detailIdsToFilter = new List<string>();
                for(IT_Contact_Association__c singleAss : contactList){
                    if(singleAss.IT_Contact_Detail__c != null){
                        detailIdsToFilter.add(singleAss.IT_Contact_Detail__c);
                    }
                }
                List<IT_Contact_Detail__c> contactDetailList = [SELECT id , Name, IT_Contact__c, IT_Contact__r.Name, IT_Contact__r.IT_Contact_Type__c FROM IT_Contact_Detail__c WHERE id NOT IN : detailIdsToFilter AND IT_Contact__r.AccountId = :fincentList[0].ER_Account_Name__c AND IT_Contact__r.IT_Type__c = 'Soc'];
                return new ResultWrapper( contactList, contactDetailList, contactList.size());
                
            }
            else{
            system.debug('AssoNOTFound');
             
            String query2 = 'SELECT id , Name, IT_Contact__c, IT_Contact__r.Name, IT_Contact__r.IT_Contact_Type__c FROM IT_Contact_Detail__c WHERE IT_Contact__r.AccountId = \''+fincentList[0].ER_Account_Name__c+'\' AND IT_Contact__r.IT_Type__c = \'Soc\' ';  
            if( sortby != NULL && sortOrder != NULL  ){
                query2 += ' ORDER BY '+ sortby+' '+ sortOrder+'  NULLS LAST';
            }
            if(!isViewAll){
                query2 +=  ' LIMIT 10';
            }
            List<IT_Contact_Detail__c> contactList2 = database.query( query2 );
            if(contactList2 != null && contactList2.size() > 0){
                system.debug('contactListFOUND');
                return new ResultWrapper( new list<IT_Contact_Association__c>(), contactList2, contactList2.size());
            }
            else return new ResultWrapper( new list<IT_Contact_Association__c>(),new list<IT_Contact_Detail__c>(),  0);        
        }
                  

    } 
    
        @AuraEnabled
    public static ContactWrapper getContactData( Integer pageSize, Integer pageNumber, String sortBy, String sortOrder, String recordId, boolean isViewAll ){
        List<ER_Financial_Center__c> fincentList = [SELECT id, ER_Account_Name__c FROM ER_Financial_Center__c WHERE id = :recordId];
        //String query = 'SELECT id,Name,IT_Client_Billing_Recepits__c,IT_Ticket_Receipts__c,ER_FinancialCenter__r.IT_Financial_Center__c FROM Contact WHERE ER_FinancialCenter__r.ER_Account_Name__c = \''+fincentList[0].ER_Account_Name__c+'\' ';
        String query = 'SELECT id,Name,IT_Contact__c,IT_Contact_Detail__c,IT_Contact__r.Name,IT_Contact__r.IT_Ticket_Receipts__c,IT_Contact__r.IT_Contact_Type__c,IT_Financial_Center__c,IT_Financial_Center__r.Name FROM IT_Contact_Association__c WHERE IT_Financial_Center__r.ER_Account_Name__c = \''+fincentList[0].ER_Account_Name__c+'\' AND (IT_Type__c = \'AM\' OR  IT_Type__c = \'Ref\') AND IT_Delivery_Site__c = null AND IT_Distribution_Point__c = null  AND IT_Contact__r.IT_Type__c = \'Ref\' ';

        if( sortby != NULL && sortOrder != NULL  ){
            query += ' ORDER BY '+ sortby+' '+ sortOrder+'  NULLS LAST';
        }
        if(!isViewAll){
           query +=  ' LIMIT 10';
        }
        
         
        
        List<IT_Contact_Association__c> contactList = database.query( query );
        if(contactList != null && contactList.size() > 0){
            system.debug('AssoFound');
            system.debug(contactList);
            Map<string , IT_Contact_Association__c> assomap = new Map<string , IT_Contact_Association__c>();
            List<string> detailIdsToFilter = new List<string>();
            for(IT_Contact_Association__c singleAss : contactList){
                if(singleAss.IT_Contact__c != null){
                    string concatIds = singleAss.IT_Contact__c;
                    concatIds += singleAss.IT_Financial_Center__c;
                    assomap.put(concatIds, singleAss );
                    detailIdsToFilter.add(singleAss.IT_Contact__c);
                }
            }
            List<IT_Contact_Association__c> deduplicatedAsso = assomap.values();
            List<Contact> noAssContactList = [SELECT id , Name, IT_Contact_Type__c, IT_Ticket_Receipts__c FROM Contact WHERE id NOT IN : detailIdsToFilter AND AccountId = :fincentList[0].ER_Account_Name__c AND IT_Type__c = 'Ref'];
            
            return new ContactWrapper( deduplicatedAsso, noAssContactList, deduplicatedAsso.size()+noAssContactList.size());
        }
        else{
            system.debug('AssoNOTFound');
             
            String query2 = 'SELECT id,Name,IT_Contact_Type__c,IT_Client_Billing_Recepits__c,IT_Ticket_Receipts__c FROM Contact WHERE AccountId = \''+fincentList[0].ER_Account_Name__c+'\' AND IT_Type__c = \'Ref\' ';  
            if( sortby != NULL && sortOrder != NULL  ){
                query2 += ' ORDER BY '+ sortby+' '+ sortOrder+'  NULLS LAST';
            }
            if(!isViewAll){
                query2 +=  ' LIMIT 10';
            }
            List<Contact> contactList2 = database.query( query2 );
            if(contactList2 != null && contactList2.size() > 0){
                system.debug('contactListFOUND');
                return new ContactWrapper( new list<IT_Contact_Association__c>(), contactList2, contactList2.size());
            }
            else return new ContactWrapper( new list<IT_Contact_Association__c>(),new list<Contact>(),  0);        
        }
            
        

    } 
    
    @AuraEnabled
    public static void updateRecords( List<sObject> detailList){
        update detailList;
    }
    
    
    public class ResultWrapper {
        
        @AuraEnabled
        public List<IT_Contact_Association__c> result {get;set;}
        @AuraEnabled
        public List<IT_Contact_Detail__c> resultDet {get;set;}
        @AuraEnabled
        public Integer totalNumberOfRecords {get;set;}
        
        public ResultWrapper( List<IT_Contact_Association__c> result, List<IT_Contact_Detail__c> resultDet, Integer totalNumberOfRecords) {
            this.result = result;
            this.resultDet = resultDet;
            this.totalNumberOfRecords = totalNumberOfRecords;
        }
    }
    
    public class ContactWrapper {
        
        @AuraEnabled
        public List<IT_Contact_Association__c> result {get;set;}
        @AuraEnabled
        public List<Contact> resultCon {get;set;}
        @AuraEnabled
        public Integer totalNumberOfRecords {get;set;}
        
        public ContactWrapper( List<IT_Contact_Association__c> result, List<Contact> resultCon,  Integer totalNumberOfRecords) {
            this.result = result;
            this.resultCon = resultCon;
            this.totalNumberOfRecords = totalNumberOfRecords;
        }
    }
    
}