src/objects/ER_Distribution_Point__c.object
<CustomObject>
    <fields>
        <fullName>IT_Data_To_Display_2__c</fullName>
        <label>Data To Display 2</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Data_To_Display_3__c</fullName>
        <label>Data To Display 3</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Data_To_Display_4__c</fullName>
        <label>Data To Display 4</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Data_Type_To_Display_3__c</fullName>
        <label>Data Type To Display 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Data_Type_To_Display</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Data_Type_To_Display_4__c</fullName>
        <label>Data Type To Display 4</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Data_Type_To_Display</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Address_to_Display__c.field-meta.xml
<CustomField>
    <fullName>IT_Address_to_Display__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Address to Display</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Data_to_Display__c.field-meta.xml
<CustomField>
    <fullName>IT_Data_to_Display__c</fullName>
    <label>Data to Display</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Data_Type_to_Display__c.field-meta.xml
<CustomField>
    <fullName>IT_Data_Type_to_Display__c</fullName>
    <label>Data Type to Display</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>IT_Data_Type_To_Display</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Distribution_Point_Address__c.field-meta.xml
<CustomField>
    <fullName>IT_Distribution_Point_Address__c</fullName>
    <formula>IT_Toponym__c &amp; &quot; &quot; &amp; ER_Street__c &amp; BR() &amp; 
ER_City__c &amp; &quot; &quot; &amp; IT_Additional_Locality__c &amp; BR() &amp; 
ER_Zip_Code__c &amp; &quot; &quot; &amp; IT_Province__c</formula>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Financial_Center__c.field-meta.xml
<CustomField>
    <fullName>IT_Financial_Center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Center</label>
    <referenceTo>ER_Financial_Center__c</referenceTo>
    <relationshipLabel>Distribution Points</relationshipLabel>
    <relationshipName>Distribution_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Free_Description_to_Display__c.field-meta.xml
<CustomField>
    <fullName>IT_Free_Description_to_Display__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Free Description to Display</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Locality_to_Display__c.field-meta.xml
<CustomField>
    <fullName>IT_Locality_to_Display__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Locality to Display</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Naming_to_Display__c.field-meta.xml
<CustomField>
    <fullName>IT_Naming_to_Display__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Naming to Display</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ER_Distribution_Point__c/fields/IT_Raw_Number_for_Display__c.field-meta.xml
<CustomField>
    <fullName>IT_Raw_Number_for_Display__c</fullName>
    <label>Raw Number for Display</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ER_City__c</fullName>
        <label>Billing City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Street__c</fullName>
        <label>Billing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Financial_Center__c</fullName>
        <externalId>true</externalId>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Hamlet__c</fullName>
        <label>Hamlet</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Service__c</fullName>
        <label>Service</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>IT_Service</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Short_Name__c</fullName>
        <label>Short Company Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Single_Client_Multiactivity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Single Client Multiactivity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Ticket_Naming__c</fullName>
        <label>Ticket Naming</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/IT_Control__c.object
<CustomObject>
    <fields>
        <fullName>IT_CLN_Exposure_code_type__c</fullName>
        <label>Exposure code type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_CLN_Line_number__c</fullName>
        <label>Line number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_CLN_Service__c</fullName>
        <label>Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_CLN_Ticket_exposure_Code__c</fullName>
        <label>Ticket exposure Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_CLN_Ticket_exposure_type__c</fullName>
        <label>Ticket exposure type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Control</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Control</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Controls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APIT22_CardInterfaceController.cls
public class APIT22_CardInterfaceController {
    @AuraEnabled
    public static string fetchDPData(id recordId){
        List<ER_Distribution_point__c> objectToReturn = [SELECT id , IT_Data_To_Display_2__c,Name,IT_Data_To_Display_3__c ,IT_Data_To_Display_4__c ,IT_Data_Type_to_Display_3__c ,IT_Data_Type_to_Display_4__c ,ER_City__c,ER_Street__c,IT_Ticket_Naming__c,IT_Validity_Start_Date__c ,IT_Hamlet__c, IT_Distribution_Point_Address__c,IT_Address_to_Display__c,IT_Data_to_Display__c,IT_Data_Type_to_Display__c,IT_Free_Description_to_Display__c,IT_Locality_to_Display__c,IT_Naming_to_Display__c,IT_Raw_Number_for_Display__c, IT_Financial_Center__r.IT_Single_Client_Multiactivity__c,IT_Financial_Center__r.IT_Service__c,IT_Financial_Center__r.ER_Account_Name__r.Name, IT_Financial_Center__r.IT_Short_Name__c FROM ER_Distribution_Point__c WHERE Id =:recordId];
        return JSON.serializePretty(objectToReturn[0]);
    }
    @AuraEnabled
    public static string fetchDataType(id recordId , string service){
        List<IT_Control__c> objectToReturn = [SELECT id , Name, IT_CLN_Ticket_exposure_Code__c, IT_CLN_Ticket_exposure_type__c, IT_CLN_Exposure_code_type__c, IT_CLN_Line_number__c  FROM IT_Control__c WHERE IT_CLN_Service__c =:service AND IT_CLN_Ticket_exposure_Code__c != null AND IT_CLN_Ticket_exposure_Code__c != ''];
        system.debug('SIZECONTROL:: '+objectToReturn.size());    
        return JSON.serializePretty(objectToReturn);
    }
    
    @AuraEnabled
    public static void updateRecord( ER_Distribution_Point__c distPoint ){
        //List<ER_Distribution_Point__c> distPointList = [SELECT id , IT_Data_To_Display_3__c, IT_Data_To_Display_4__c, IT_Data_Type_to_Display_3__c, IT_Data_Type_to_Display_4__c FROM ER_Distribution_Point__c WHERE Id =:distPoint.Id];
        if(distPoint.IT_Data_To_Display_2__c != null || distPoint.IT_Data_To_Display_3__c != null || distPoint.IT_Data_Type_to_Display_3__c != null || distPoint.IT_Data_To_Display_4__c != null || distPoint.IT_Data_Type_to_Display_4__c != null ){
            if(distPoint.IT_Data_To_Display_2__c != null){
                distPoint.IT_Raw_Number_for_Display__c = 2;
                distPoint.IT_Data_To_Display__c = distPoint.IT_Data_To_Display_2__c;
                update distPoint;
            }
            if(distPoint.IT_Data_To_Display_3__c != null || distPoint.IT_Data_Type_to_Display_3__c != null){
                distPoint.IT_Raw_Number_for_Display__c = 3;
                distPoint.IT_Data_To_Display__c = distPoint.IT_Data_To_Display_3__c;
                distPoint.IT_Data_Type_to_Display__c = distPoint.IT_Data_Type_to_Display_3__c;
                update distPoint;
            }
            if(distPoint.IT_Data_To_Display_4__c != null || distPoint.IT_Data_Type_to_Display_4__c != null){
                distPoint.IT_Raw_Number_for_Display__c = 4;
                distPoint.IT_Data_To_Display__c = distPoint.IT_Data_To_Display_4__c;
                distPoint.IT_Data_Type_to_Display__c = distPoint.IT_Data_Type_to_Display_4__c;
                update distPoint;
            }
        }
        else{
            update distPoint;
        }
    }
    
}