src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>ER_Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Account_Active__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (Active)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers (Active)</relationshipLabel>
        <relationshipName>Financial_Centers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Account_Closed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (Closed)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers (Closed)</relationshipLabel>
        <relationshipName>Financial_Centers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Account_Provisioning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (Provisioning)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers (Provisioning)</relationshipLabel>
        <relationshipName>Financial_Centers3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Client_Status__c</fullName>
        <label>Client Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <label>PROVISIONAL CUSTOMER</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <label>IN DEFINITION</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>IN DEFINING ONLINE</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>TO ACTIVATE</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>ACTIVE</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>CANCELED</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>CANCELED NON-PAYMENT</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>SUSPENDED</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>TO ARRANGE</label>
                </value>
                <value>
                    <fullName>07</fullName>
                    <label>POTENTIAL ESPADA</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>CLIENTS WAITING FOR THE CODE 6</label>
                </value>
                <value>
                    <fullName>98</fullName>
                    <label>CUSTOMERS IN DEF. PROBABLE DELETE</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>TO CANCEL</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>DEFINITELY CANCELED</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/BAIT03_BatchPopulateCorrectLookupAccount.cls
global class BAIT03_BatchPopulateCorrectLookupAccount implements Database.Batchable<Sobject>, Database.Stateful {

    private String query = 'SELECT Id, IT_Account_Active__c, IT_Account_Provisioning__c, IT_Account_Closed__c, ER_Account_Name__c, IT_Client_Status__c FROM ER_Financial_Center__c WHERE (IT_Account_Active__c = null And IT_Account_Provisioning__c = null And IT_Account_Closed__c = null) Or (IT_Account_Active__c = null And (IT_Client_Status__c = \'02\' Or IT_Client_Status__c = \'05\')) Or 	(IT_Account_Provisioning__c = null And IT_Client_Status__c = \'01\') Or (IT_Account_Closed__c = null And IT_Client_Status__c != \'02\' And IT_Client_Status__c != \'05\' And IT_Client_Status__c != \'01\')';
    List<ER_Financial_center__c> updateListFC = new List<ER_Financial_center__c>();
    Map<String, ER_Financial_Center__c> mapFCUpdateId = new Map<String, ER_Financial_Center__c>();
    
    global BAIT03_BatchPopulateCorrectLookupAccount(){
        updateListFC = new List<ER_Financial_center__c>();
        mapFCUpdateId = new Map<String, ER_Financial_Center__c>();      
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('query: '+query);
        List<ER_Financial_Center__c> listFC = Database.query(query);
        for(ER_Financial_Center__c singleItem : listFC){
            if(singleItem.IT_Client_Status__c == '02'){
                singleItem.IT_Account_Active__c = singleItem.ER_Account_Name__c;
                singleItem.IT_Account_Provisioning__c = null;
                singleItem.IT_Account_Closed__c = null;    
            }else if(singleItem.IT_Client_Status__c == '01' || singleItem.IT_Client_Status__c == '05'){
                singleItem.IT_Account_Provisioning__c = singleItem.ER_Account_Name__c;
                singleItem.IT_Account_Active__c = null;
                singleItem.IT_Account_Closed__c = null;
            }else{
                singleItem.IT_Account_Closed__c = singleItem.ER_Account_Name__c;
                singleItem.IT_Account_Active__c = null;
                singleItem.IT_Account_Provisioning__c = null;
            }
            mapFCUpdateId.put(singleItem.Id, singleItem);
        }
        return  Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ER_Financial_center__c> scope){
        System.debug('scope: '+scope);
        for(ER_Financial_Center__c singleItemFC : scope){
            ER_Financial_Center__c newFc = new ER_Financial_Center__c();
            if(mapFCUpdateId != null && mapFCUpdateId.size() > 0 && mapFCUpdateId.keyset().contains(singleItemFC.Id)){
                newFc = mapFCUpdateId.get(singleItemFC.Id);
                updateListFC.add(newFc);
            }    
        }
    }   
    
    global void finish(Database.BatchableContext BC){  
        System.debug('updateListFC::: '+updateListFC);
        System.debug('updateListFC.size::: '+updateListFC.size());
    }     
}