src/objects/ER_Financial_Center__c.object
<CustomObject>
    <fields>
        <fullName>IT_Account_Active__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (Active)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers (Active)</relationshipLabel>
        <relationshipName>Financial_Centers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Account_Closed__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (Closed)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers (Closed)</relationshipLabel>
        <relationshipName>Financial_Centers2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Account_Provisioning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (Provisioning)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Centers (Provisioning)</relationshipLabel>
        <relationshipName>Financial_Centers3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Client_Status__c</fullName>
        <label>Client Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>00</fullName>
                    <label>PROVISIONAL CUSTOMER</label>
                </value>
                <value>
                    <fullName>01</fullName>
                    <label>IN DEFINITION</label>
                </value>
                <value>
                    <fullName>12</fullName>
                    <label>IN DEFINING ONLINE</label>
                </value>
                <value>
                    <fullName>05</fullName>
                    <label>TO ACTIVATE</label>
                </value>
                <value>
                    <fullName>02</fullName>
                    <label>ACTIVE</label>
                </value>
                <value>
                    <fullName>03</fullName>
                    <label>CANCELED</label>
                </value>
                <value>
                    <fullName>13</fullName>
                    <label>CANCELED NON-PAYMENT</label>
                </value>
                <value>
                    <fullName>04</fullName>
                    <label>SUSPENDED</label>
                </value>
                <value>
                    <fullName>06</fullName>
                    <label>TO ARRANGE</label>
                </value>
                <value>
                    <fullName>07</fullName>
                    <label>POTENTIAL ESPADA</label>
                </value>
                <value>
                    <fullName>11</fullName>
                    <label>CLIENTS WAITING FOR THE CODE 6</label>
                </value>
                <value>
                    <fullName>98</fullName>
                    <label>CUSTOMERS IN DEF. PROBABLE DELETE</label>
                </value>
                <value>
                    <fullName>10</fullName>
                    <label>TO CANCEL</label>
                </value>
                <value>
                    <fullName>08</fullName>
                    <label>DEFINITELY CANCELED</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Financial Centers</relationshipLabel>
        <relationshipName>Financial_Centers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IT_Sales_Manager_txt__c</fullName>
        <label>Sales Manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Financial Center</label>
    <nameField>
        <label>Financial Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Centers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>IT_Line_Type__c</fullName>
        <label>Line Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>Papier</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>Expense Management</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>Incentive</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>Card</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>PSP</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APIT00_RunTimeSegment.cls
public class APIT00_RunTimeSegment {
    @AuraEnabled
public static String CheckSegment(string AccountId)
{ 
    string SalesName=USERINFO.getLastName()+' '+userinfo.getFirstName();
    List <String> Result= new  List <String>() ;
    String myLine= [Select IT_Line_Type__c From User Where Id = :UserInfo.getUserId()][0].IT_Line_Type__c;
   list <ER_Financial_Center__c>  FCs= [SELECT ID,IT_Client_Status__c,IT_Product2__r.IT_Line_Type__c,IT_Sales_Manager_txt__c FROM ER_Financial_Center__c
                                         WHERE IT_Account_Active__c=:AccountId or IT_Account_Closed__c=:AccountId or IT_Account_Provisioning__c=:AccountId] ;
    IF  (FCs !=null) {
    for (ER_Financial_Center__c  fc : FCs) {
        
           system.debug(fc.IT_Sales_Manager_txt__c+'-'+SalesName);
           if (fc.IT_Sales_Manager_txt__c==SalesName){
            
               if(fc.IT_Client_Status__c=='02'){
                   Result.add('My Customer');
               }
           }else {
               if(fc.IT_Product2__r.IT_Line_Type__c==myLine){
                  if(fc.IT_Client_Status__c=='02'){
                   Result.add('Customer');
                       }else{
                           Result.add('Inactive');
                       }
               }else{
                    Result.add('Prospect');
               }
                   
           }
       }
    
    IF (RESULT.contains('My Customer')) {
        return 'My Customer';
    }else{
        IF (RESULT.contains('Customer')){
            return 'Customer';
        }else{
            IF (RESULT.contains('Inactive')){
              return 'Inactive';  
            }else{
                return'Prospect';
            }
        }
    }
       
    }
    return '';
      
}
}