src/objects/IT_Group__c.object
<CustomObject>
    <fields>
        <fullName>IT_Group_Code__c</fullName>
        <externalId>true</externalId>
        <label>Group Code</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IT_Group_Code__c.object
<CustomObject>
    <fields>
        <fullName>IT_Client_Code__c</fullName>
        <label>Client Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Group_Code__c</fullName>
        <label>Group Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>IT_Group__c</referenceTo>
        <relationshipLabel>Groups Code</relationshipLabel>
        <relationshipName>Groups_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Code</label>
    <nameField>
        <label>Group Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BAIT01_BatchGroupAssociations.cls
global class BAIT01_BatchGroupAssociations implements Database.Batchable<Sobject>, Database.Stateful {

    private String query = 'SELECT id, name, IT_Group_Code__c, IT_Client_Code__c From IT_Group_Code__c Where IT_Group__c = \'\'';
    global Map<String, String> idGroups = new Map<String, String>(); 

    global BAIT01_BatchGroupAssociations(){
        idGroups = new Map<String, String>();    
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('query: '+query);
        List<IT_Group_Code__c> listGroupCode = Database.query(query);
        List<String> groupNames = new List<String>();
        List<IT_Group__c> groupList = new List<IT_Group__c>();
        for(IT_Group_Code__c item : listGroupCode){
            groupNames.add(item.IT_Group_Code__c);
        }
        groupList = [Select id, name, IT_Group_Code__c From IT_Group__c Where IT_Group_Code__c IN: groupNames];
        if(groupList != null && groupList.size() > 0){
            for(IT_Group__c itemGroup : groupList){
                idGroups.put(itemGroup.IT_Group_Code__c, itemGroup.Id);    
            }    
        }
        return  Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<IT_Group_Code__c> scope){
        System.debug('scope: '+scope);
        System.debug('idGroups: '+idGroups);
        List<IT_Group_Code__c> upGroupCode = new List<IT_Group_Code__c>();
        List<IT_Group_Code__c> groupCodeOK = new List<IT_Group_Code__c>();
        groupCodeOK  = scope;
        for(IT_Group_Code__c itemGroupCode : groupCodeOK){
            if(idGroups != null && idGroups.size() > 0 && idGroups.keyset().contains(itemGroupCode.IT_Group_Code__c)){
                itemGroupCode.IT_Group__c = idGroups.get(itemGroupCode.IT_Group_Code__c);
                upGroupCode.add(itemGroupCode);
            }    
        }
        if(upGroupCode != null && upGroupCode.size() > 0)
            update upGroupCode;
    }   
    
    global void finish(Database.BatchableContext BC){

    }     
}