src/objects/IT_PDF_TemplateMdt__mdt.object
<CustomObject>
    <fields>
        <fullName>IT_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_HtmlForPdf__c</fullName>
        <label>HtmlForPdf</label>
        <length>130768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IT_Object_Name__c</fullName>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>IT_Welfare_Project__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PDF Template</label>
    <pluralLabel>PDF Templates</pluralLabel>
</CustomObject>

src/objects/IT_Plan__c.object
<CustomObject>
    <fields>
        <fullName>IT_Welfare_Project__c</fullName>
        <label>Welfare Project</label>
        <referenceTo>IT_Welfare_Project__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan</label>

    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IT_Replace_ItemMdt__mdt.object
<CustomObject>
    <fields>
        <fullName>IT_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IT_Child_Object__c</fullName>
        <label>Child Object</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Field_Name__c</fullName>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Image__c</fullName>
        <label>Image</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IT_Object_Name__c</fullName>
        <label>Object Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                    <default>true</default>
                    <label>Account</label>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>IT_Welfare_Project__c</fullName>
                </value>
                <value>
                    <fullName>IT_Plan__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IT_PDF_Template__c</fullName>
        <label>PDF Template</label>
        <referenceTo>IT_PDF_TemplateMdt__mdt</referenceTo>
        <relationshipLabel>Replace Items</relationshipLabel>
        <relationshipName>Replace_Items</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>IT_Placeholder__c</fullName>
        <label>Placeholder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Replace_Type__c</fullName>
        <label>Replace Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                    <default>true</default>
                    <label>Parent</label>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Replace Item</label>
    <pluralLabel>Replace Items</pluralLabel>
</CustomObject>

src/objects/IT_Welfare_Project__c.object
<CustomObject>
    <label>Welfare Project</label>
    <nameField>
        <label>Welfare Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Welfare Project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APIT09_CreatePDFController_Test.cls
@isTest
public class APIT09_CreatePDFController_Test {
    @isTest
    static void TestCreatePdf() {
        IT_Welfare_Project__c weProTest = APIT14_DataFactory.create_WelfareProject();
        insert weProTest;
        IT_Plan__c planTest = APIT14_DataFactory.create_Plan(weProTest.Id);
        //insert planTest;
        IT_PDF_TemplateMdt__mdt pdfTemp = [Select MasterLabel, IT_Active__c, IT_Object_Name__c, IT_HtmlForPdf__c, (Select IT_Active__c, IT_Child_Object__c, IT_Field_Name__c, IT_Placeholder__c, IT_Replace_Type__c, IT_Object_Name__c, IT_PDF_Template__c, IT_Image__c From Replace_Items__r) From IT_PDF_TemplateMdt__mdt limit 1];

        APIT09_CreatePDFController.ShowPdf(pdfTemp.Id, weProTest.Id, 'IT_Welfare_Project__c'); 
        APIT09_CreatePDFController.ShowPdfList('IT_Welfare_Project__c');

        ApexPages.currentPage().getParameters().put('templateId', String.valueOf(pdfTemp.Id));
    	ApexPages.currentPage().getParameters().put('templateObjectName', String.valueOf('IT_Welfare_Project__c'));
        ApexPages.currentPage().getParameters().put('templateObjectId', String.valueOf(weProTest.Id));
        APIT09_CreatePDFController  testAccPlan = new APIT09_CreatePDFController();

        //APIT09_CreatePDFController.APIT09_CreatePDFControllerReplace(pdfTemp.Id, 'IT_Welfare_Project__c', weProTest.Id);              


    }
}