src/objects/IT_Usage__c.object
<CustomObject>
    <label>Usage</label>
    <nameField>
        <displayFormat>2020-{0000}</displayFormat>
        <label>Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>IT_Subscription_Product_Charge__c</fullName>
        <label>Subscription Product &amp; Charge</label>
        <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
        <relationshipLabel>Usage</relationshipLabel>
        <relationshipName>Usage</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/classes/VFCIT27_Installment_Controller.cls
public class VFCIT27_Installment_Controller {
     
    public String[] SelectedUsageIDs{get;set;}
    public String ID_Sub {get;set;}
    
    public VFCIT27_Installment_Controller(ApexPages.StandardSetController listcontroller){
        SelectedUsageIDs = new String[]{};
        for(IT_Usage__c itUsa : (IT_Usage__c[])listcontroller.getSelected()){
            SelectedUsageIDs.add(itUsa.Id);
        } 
       
        System.debug('SelectedUsageIDs:  '+SelectedUsageIDs);
        
        ID_Sub=([SELECT IT_Subscription_Product_Charge__c
                 FROM IT_Usage__c
                 WHERE id in: SelectedUsageIDs LIMIT 1].IT_Subscription_Product_Charge__c);
                 System.debug('ID_Sub'+ ID_Sub); 
    }
    
}