src/objects/IT_Usage__c.object
<CustomObject>
    <label>Usage</label>
    <nameField>
        <displayFormat>2020-{0000}</displayFormat>
        <label>Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IT_Usage__c/fields/Subscription_Product_Charge__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Product_Charge__c</fullName>
    <label>Subscription Product &amp; Charge</label>
    <referenceTo>Zuora__SubscriptionProductCharge__c</referenceTo>
    <relationshipLabel>Usage</relationshipLabel>
    <relationshipName>Usage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VFCIT00_Installment_Controller.cls
public class VFCIT00_Installment_Controller {
     
    public String[] SelectedUsageIDs{get;set;}
    public String ID_Sub {get;set;}
    
    public VFCIT00_Installment_Controller(ApexPages.StandardSetController listcontroller){
        SelectedUsageIDs = new String[]{};
        for(IT_Usage__c itUsa : (IT_Usage__c[])listcontroller.getSelected()){
            SelectedUsageIDs.add(itUsa.Id);
        } 
       
        System.debug('SelectedUsageIDs:  '+SelectedUsageIDs);
        
        ID_Sub=([SELECT Subscription_Product_Charge__c
                 FROM IT_Usage__c
                 WHERE id in: SelectedUsageIDs LIMIT 1].Subscription_Product_Charge__c);
                 System.debug('ID_Sub'+ ID_Sub); 
    }
    
    //Flow.Interview.IT00_InstallmentUsage myflow = new Flow.Interview.IT00_InstallmentUsage() ;
     //    Flow.Interview.IT00_InstallmentUsage myflow { get; set; }

    	// public String getVarValue() {
        //	if (myflow == null) {
          // 	 System.debug('myflow'+myflow);
        //	    return 'Home';
       	// 	}
        //	else {
         //   	System.debug('VarValue ');
          // 		return (String)myflow.ID_For_Page;
        //	}    
   		//}
 
}