src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ER_Store_Name__c</fullName>
        <label>Store Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Terminal__c</fullName>
        <label>Terminal</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Don&apos;t know</fullName>
                    <default>true</default>
                    <label>Don&apos;t know</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ER_VAT_Number__c</fullName>
        <label>VAT Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ER_Language__c</fullName>
        <defaultValue>$User.ER_BUText__c</defaultValue>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ER_Language</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/ER_Language.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>NL</fullName>
    </customValue>
    <customValue>
        <fullName>EN</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>CZ</fullName>
    </customValue>
    <customValue>
        <fullName>SK</fullName>
    </customValue>
    <customValue>
        <fullName>PL</fullName>
    </customValue>
    <customValue>
        <fullName>HU</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
</GlobalValueSet>

src/classes/APER03_Lead_CreateFinancialCenter_Test.cls
@isTest
public class APER03_Lead_CreateFinancialCenter_Test {
/*
----------------------------------------------------------------------
-- - Name          : APER03_Lead_CreateFinancialCenter_Test
-- - Author        : AAB
-- - Description   : Test class related to the Apex classes cited below
					- APER03_Lead_CreateFinancialCenter
-- Maintenance History:
--
-- Date         Name  				Version  	Remarks 
-- -----------  ----------- 		--------  	---------------------------------------
-- 17-JUL-2018  AAB    				1.0      	Initial version 
---------------------------------------------------------------------------------------
*/
     public static List<Lead> createLeadsStandard(Integer numlds, Id recordType, String vatNumber,  Boolean isToInsert) {
        List<Lead> leads = new List<Lead>();
        
         
         // Retrieve picklist values
        Schema.DescribeFieldResult fieldResult =
 				Lead.Status.getDescribe();
   		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         
        for(Integer i=0;i<numlds;i++) {
            Lead ld = new Lead(
                ER_Store_Name__c = 'my store',
                LastName ='lastname' + i,
                FirstName ='firstname' + i,
                Status = ple[0].getValue(),
            	RecordTypeId = recordType,
            	ER_VAT_Number__c = vatNumber,
                Company = 'Edenred',
                Email = 'test@salesforce.com',
                Street = '178, boulevard Gabriel Péri ',
            	City = 'Malakoff',
                ER_Terminal__c = 'Yes',
                PostalCode = '92240',
                ER_Language__c = 'EN'
            	);
            leads.add(ld);
        }
         
         if (isToInsert) {
             insert leads;
         } 

        return leads;
    }
}