src/objects/zqu__Quote__c.object
<CustomObject>
    <fields>
        <fullName>IT_Cod_Cli_Padre__c</fullName>
        <label>Cod_Cli_Padre</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Recurring_Start_Date__c</fullName>
        <defaultValue>Today()+365</defaultValue>
        <label>IT_Recurring_Start_Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/classes/TRIT28_QuoteOnDemandSyncTrigger_Test.cls
@isTest
public class TRIT28_QuoteOnDemandSyncTrigger_Test {
    static testMethod void createRecord() {
        RecordType quoteRecordType =  [SELECT Id FROM RecordType where SobjectType='zqu__Quote__c' and Developername='Amendment' Limit 1];
      	zqu__Quote__c quoTest = new zqu__Quote__c(RecordTypeId = quoteRecordType.Id,
                                                  name='testQuote',
                                                  IT_Cod_Cli_Padre__c='33333',
                                               	  IT_Recurring_Start_Date__c=System.today());
        insert quoTest;

        quoTest.IT_Recurring_Start_Date__c=System.today()+3;
        update quoTest;
        
        delete quoTest;
    }
    
}